export interface ILRLink {
  id: string;
  name: string;
  component: 'himalayan' | 'peninsular';
  fromRiver: string;
  toRiver: string;
  states: string[];
  path: string; // SVG path in 680x740 coordinate space
  nodeFrom: { x: number; y: number; label: string };
  nodeTo: { x: number; y: number; label: string };
  status: 'In Progress' | 'DPR Ready' | 'Feasibility Done' | 'Operational' | 'Under Investigation';
  lengthKm: number;
  waterTransferBCM: number;
  description: string;
}

export interface ILRRiverNode {
  id: string;
  name: string;
  x: number;
  y: number;
  basin: string;
}

// 9 Major river label positions corresponding to the reference mockup
export const ILR_RIVER_NODES: ILRRiverNode[] = [
  { id: 'indus', name: 'Indus', x: 200, y: 155, basin: 'Indus Basin' },
  { id: 'ganga', name: 'Ganga', x: 375, y: 245, basin: 'Ganga Basin' },
  { id: 'brahmaputra', name: 'Brahmaputra', x: 555, y: 220, basin: 'Brahmaputra Basin' },
  { id: 'narmada', name: 'Narmada', x: 260, y: 350, basin: 'Narmada Basin' },
  { id: 'tapi', name: 'Tapi', x: 245, y: 395, basin: 'Tapi Basin' },
  { id: 'mahanadi', name: 'Mahanadi', x: 440, y: 380, basin: 'Mahanadi Basin' },
  { id: 'godavari', name: 'Godavari', x: 350, y: 445, basin: 'Godavari Basin' },
  { id: 'krishna', name: 'Krishna', x: 335, y: 510, basin: 'Krishna Basin' },
  { id: 'cauvery', name: 'Cauvery', x: 330, y: 615, basin: 'Cauvery Basin' },
];

// Himalayan Component: 14 Links
export const HIMALAYAN_LINKS: ILRLink[] = [
  {
    id: 'him-1',
    name: 'Brahmaputra–Ganga (Manas–Sankosh–Tista–Ganga)',
    component: 'himalayan',
    fromRiver: 'Brahmaputra (Manas/Sankosh)',
    toRiver: 'Ganga',
    states: ['Assam', 'West Bengal', 'Bihar'],
    path: 'M 540 225 Q 490 235 445 250',
    nodeFrom: { x: 540, y: 225, label: 'Jogighopa' },
    nodeTo: { x: 445, y: 250, label: 'Farakka' },
    status: 'Feasibility Done',
    lengthKm: 457,
    waterTransferBCM: 24.3,
    description: 'Transfers substantial surplus monsoon flows from Manas and Sankosh in Brahmaputra basin to Ganga upstream of Farakka Barrage.',
  },
  {
    id: 'him-2',
    name: 'Kosi–Ghagra',
    component: 'himalayan',
    fromRiver: 'Kosi',
    toRiver: 'Ghagra',
    states: ['Bihar', 'Uttar Pradesh'],
    path: 'M 435 245 Q 395 240 355 240',
    nodeFrom: { x: 435, y: 245, label: 'Chatra' },
    nodeTo: { x: 355, y: 240, label: 'Ghagra' },
    status: 'Feasibility Done',
    lengthKm: 215,
    waterTransferBCM: 8.7,
    description: 'Diverts surplus water of Kosi river to Ghagra river basin to prevent northern Bihar floods and supply irrigation to eastern UP.',
  },
  {
    id: 'him-3',
    name: 'Gandak–Ganga',
    component: 'himalayan',
    fromRiver: 'Gandak',
    toRiver: 'Ganga',
    states: ['Bihar', 'Uttar Pradesh'],
    path: 'M 390 235 Q 380 250 375 260',
    nodeFrom: { x: 390, y: 235, label: 'Valmikinagar' },
    nodeTo: { x: 375, y: 260, label: 'Patna' },
    status: 'Feasibility Done',
    lengthKm: 142,
    waterTransferBCM: 5.2,
    description: 'Enables direct transfer from Gandak barrage into Ganga mainstem for downstream drought mitigation.',
  },
  {
    id: 'him-4',
    name: 'Ghagra–Yamuna',
    component: 'himalayan',
    fromRiver: 'Ghagra',
    toRiver: 'Yamuna',
    states: ['Uttar Pradesh', 'Haryana'],
    path: 'M 355 240 Q 300 240 245 235',
    nodeFrom: { x: 355, y: 240, label: 'Faizabad' },
    nodeTo: { x: 245, y: 235, label: 'Delhi/Yamuna' },
    status: 'Feasibility Done',
    lengthKm: 416,
    waterTransferBCM: 13.8,
    description: 'Connects Ghagra to Yamuna near Delhi to supply drinking water to NCR and irrigate arid plains of southern Haryana.',
  },
  {
    id: 'him-5',
    name: 'Sarda–Yamuna',
    component: 'himalayan',
    fromRiver: 'Sarda',
    toRiver: 'Yamuna',
    states: ['Uttarakhand', 'Uttar Pradesh', 'Haryana'],
    path: 'M 290 195 Q 260 215 235 225',
    nodeFrom: { x: 290, y: 195, label: 'Pancheshwar' },
    nodeTo: { x: 235, y: 225, label: 'Hathnikund' },
    status: 'DPR Ready',
    lengthKm: 384,
    waterTransferBCM: 11.6,
    description: 'Originates at Pancheshwar High Dam site on India-Nepal border, feeding western Uttar Pradesh and Haryana canals.',
  },
  {
    id: 'him-6',
    name: 'Yamuna–Rajasthan',
    component: 'himalayan',
    fromRiver: 'Yamuna',
    toRiver: 'Rajasthan Desert Canals',
    states: ['Haryana', 'Rajasthan'],
    path: 'M 235 235 Q 210 260 190 280',
    nodeFrom: { x: 235, y: 235, label: 'Okhla' },
    nodeTo: { x: 190, y: 280, label: 'Jhunjhunu' },
    status: 'Feasibility Done',
    lengthKm: 342,
    waterTransferBCM: 6.4,
    description: 'Carries surplus monsoon Yamuna waters to drought-prone Shekhawati districts of Rajasthan.',
  },
  {
    id: 'him-7',
    name: 'Rajasthan–Sabarmati',
    component: 'himalayan',
    fromRiver: 'Rajasthan Canals',
    toRiver: 'Sabarmati',
    states: ['Rajasthan', 'Gujarat'],
    path: 'M 190 280 Q 185 320 195 350',
    nodeFrom: { x: 190, y: 280, label: 'Marwar' },
    nodeTo: { x: 195, y: 350, label: 'Sabarmati' },
    status: 'Feasibility Done',
    lengthKm: 378,
    waterTransferBCM: 4.8,
    description: 'Extends northern canal network southward across the Aravalli range into northern Gujarat basins.',
  },
  {
    id: 'him-8',
    name: 'Chunar–Sone Barrage',
    component: 'himalayan',
    fromRiver: 'Ganga (Chunar)',
    toRiver: 'Sone Barrage (Indrapuri)',
    states: ['Uttar Pradesh', 'Bihar'],
    path: 'M 350 265 L 390 280',
    nodeFrom: { x: 350, y: 265, label: 'Chunar' },
    nodeTo: { x: 390, y: 280, label: 'Indrapuri' },
    status: 'Feasibility Done',
    lengthKm: 149,
    waterTransferBCM: 3.9,
    description: 'Connects mainstem Ganga at Chunar to Sone canal system, augmenting critical rabi crop irrigation in southwestern Bihar.',
  },
  {
    id: 'him-9',
    name: 'Sone Dam–Southern Tributaries of Ganga',
    component: 'himalayan',
    fromRiver: 'Sone Dam (Kadwan)',
    toRiver: 'Southern Tributaries of Ganga',
    states: ['Jharkhand', 'Bihar'],
    path: 'M 390 280 Q 410 290 435 290',
    nodeFrom: { x: 390, y: 280, label: 'Kadwan' },
    nodeTo: { x: 435, y: 290, label: 'Kiul/Badua' },
    status: 'Feasibility Done',
    lengthKm: 182,
    waterTransferBCM: 4.1,
    description: 'Transfers stored monsoon water from Kadwan reservoir to chronically drought-prone south Bihar plateaus.',
  },
  {
    id: 'him-10',
    name: 'Ganga–Damodar–Subernarekha',
    component: 'himalayan',
    fromRiver: 'Ganga',
    toRiver: 'Damodar & Subernarekha',
    states: ['West Bengal', 'Jharkhand'],
    path: 'M 445 260 Q 440 295 435 330',
    nodeFrom: { x: 445, y: 260, label: 'Katwa' },
    nodeTo: { x: 435, y: 330, label: 'Jamshedpur' },
    status: 'Feasibility Done',
    lengthKm: 286,
    waterTransferBCM: 5.7,
    description: 'Links Lower Ganga with industrial belts of Damodar valley and mining regions along Subernarekha.',
  },
  {
    id: 'him-11',
    name: 'Subernarekha–Mahanadi',
    component: 'himalayan',
    fromRiver: 'Subernarekha',
    toRiver: 'Mahanadi',
    states: ['Jharkhand', 'Odisha'],
    path: 'M 435 330 Q 430 355 440 380',
    nodeFrom: { x: 435, y: 330, label: 'Ghatsila' },
    nodeTo: { x: 440, y: 380, label: 'Cuttack' },
    status: 'Feasibility Done',
    lengthKm: 198,
    waterTransferBCM: 4.4,
    description: 'Forms the vital geographic bridge connecting the Himalayan component to the Peninsular river grid.',
  },
  {
    id: 'him-12',
    name: 'Kosi–Mechi',
    component: 'himalayan',
    fromRiver: 'Kosi',
    toRiver: 'Mechi (Mahananda basin)',
    states: ['Bihar', 'West Bengal'],
    path: 'M 435 245 L 465 248',
    nodeFrom: { x: 435, y: 245, label: 'Birpur' },
    nodeTo: { x: 465, y: 248, label: 'Kishanganj' },
    status: 'DPR Ready',
    lengthKm: 117,
    waterTransferBCM: 2.8,
    description: 'Interlinks Kosi with Mechi river in northern Bihar to irrigate over 2.14 lakh hectares in Seemanchal.',
  },
  {
    id: 'him-13',
    name: 'Farakka–Sunderbans',
    component: 'himalayan',
    fromRiver: 'Ganga (Farakka)',
    toRiver: 'Sunderbans Delta Channels',
    states: ['West Bengal'],
    path: 'M 445 250 Q 460 280 470 310',
    nodeFrom: { x: 445, y: 250, label: 'Farakka' },
    nodeTo: { x: 470, y: 310, label: 'Sundarbans' },
    status: 'Feasibility Done',
    lengthKm: 130,
    waterTransferBCM: 3.2,
    description: 'Flushes hypersaline estuarine mangroves with sweet fresh Ganga water to preserve Sundarban biodiversity.',
  },
  {
    id: 'him-14',
    name: 'Jogighopa–Tista–Farakka',
    component: 'himalayan',
    fromRiver: 'Brahmaputra (Jogighopa)',
    toRiver: 'Ganga (Farakka) via Tista',
    states: ['Assam', 'West Bengal'],
    path: 'M 540 225 Q 490 230 445 250',
    nodeFrom: { x: 540, y: 225, label: 'Jogighopa' },
    nodeTo: { x: 445, y: 250, label: 'Ganga' },
    status: 'DPR Ready',
    lengthKm: 504,
    waterTransferBCM: 28.5,
    description: 'The monumental anchor link of the Himalayan grid, bypassing Bangladesh to deliver 28.5 BCM to northern & central India.',
  },
];

// Peninsular Component: 16 Links
export const PENINSULAR_LINKS: ILRLink[] = [
  {
    id: 'pen-1',
    name: 'Mahanadi (Manibhadra)–Godavari (Dowleswaram)',
    component: 'peninsular',
    fromRiver: 'Mahanadi',
    toRiver: 'Godavari',
    states: ['Odisha', 'Andhra Pradesh'],
    path: 'M 440 380 Q 410 415 390 445',
    nodeFrom: { x: 440, y: 380, label: 'Manibhadra' },
    nodeTo: { x: 390, y: 445, label: 'Dowleswaram' },
    status: 'DPR Ready',
    lengthKm: 827,
    waterTransferBCM: 11.2,
    description: 'Diverts 11.2 BCM surplus water from Mahanadi basin to Godavari, opening irrigation to coastal Odisha and Andhra Pradesh.',
  },
  {
    id: 'pen-2',
    name: 'Godavari (Inchampalli)–Krishna (Nagarjunasagar)',
    component: 'peninsular',
    fromRiver: 'Godavari',
    toRiver: 'Krishna',
    states: ['Telangana', 'Andhra Pradesh'],
    path: 'M 350 445 Q 345 475 340 500',
    nodeFrom: { x: 350, y: 445, label: 'Inchampalli' },
    nodeTo: { x: 340, y: 500, label: 'Nagarjunasagar' },
    status: 'DPR Ready',
    lengthKm: 299,
    waterTransferBCM: 16.4,
    description: 'Pumps surplus monsoon Godavari waters into Nagarjunasagar reservoir to relieve dry Rayalaseema and Nalgonda.',
  },
  {
    id: 'pen-3',
    name: 'Godavari (Inchampalli Low Dam)–Krishna (Tail Pond)',
    component: 'peninsular',
    fromRiver: 'Godavari',
    toRiver: 'Krishna (Tail Pond)',
    states: ['Telangana', 'Andhra Pradesh'],
    path: 'M 350 445 Q 355 480 350 505',
    nodeFrom: { x: 350, y: 445, label: 'Inchampalli' },
    nodeTo: { x: 350, y: 505, label: 'Tail Pond' },
    status: 'Feasibility Done',
    lengthKm: 278,
    waterTransferBCM: 14.2,
    description: 'Alternative low-head alignment designed to reduce submergence of forest lands along the Godavari gorge.',
  },
  {
    id: 'pen-4',
    name: 'Godavari (Polavaram)–Krishna (Vijayawada)',
    component: 'peninsular',
    fromRiver: 'Godavari',
    toRiver: 'Krishna',
    states: ['Andhra Pradesh'],
    path: 'M 390 445 Q 380 480 365 505',
    nodeFrom: { x: 390, y: 445, label: 'Polavaram' },
    nodeTo: { x: 365, y: 505, label: 'Prakasam Barrage' },
    status: 'Operational',
    lengthKm: 174,
    waterTransferBCM: 5.3,
    description: 'Operationalized in Andhra Pradesh through the Pattiseema Lift Scheme, diverting 80 TMC annually into Prakasam Barrage.',
  },
  {
    id: 'pen-5',
    name: 'Krishna (Almatti)–Pennar (Bukkapatnam)',
    component: 'peninsular',
    fromRiver: 'Krishna',
    toRiver: 'Pennar',
    states: ['Karnataka', 'Andhra Pradesh'],
    path: 'M 280 490 Q 285 530 295 560',
    nodeFrom: { x: 280, y: 490, label: 'Almatti' },
    nodeTo: { x: 295, y: 560, label: 'Bukkapatnam' },
    status: 'Feasibility Done',
    lengthKm: 341,
    waterTransferBCM: 3.8,
    description: 'Supplies chronically drought-afflicted Bellary and Anantapur plateau districts with Upper Krishna storage.',
  },
  {
    id: 'pen-6',
    name: 'Krishna (Srisailam)–Pennar (Mylavaram)',
    component: 'peninsular',
    fromRiver: 'Krishna',
    toRiver: 'Pennar',
    states: ['Andhra Pradesh'],
    path: 'M 335 505 Q 330 535 325 560',
    nodeFrom: { x: 335, y: 505, label: 'Srisailam' },
    nodeTo: { x: 325, y: 560, label: 'Mylavaram' },
    status: 'Feasibility Done',
    lengthKm: 204,
    waterTransferBCM: 4.2,
    description: 'Connects Srisailam reservoir to Pennar river basin through the Kurnool–Cuddapah canal alignment.',
  },
  {
    id: 'pen-7',
    name: 'Krishna (Nagarjunasagar)–Pennar (Somasila)',
    component: 'peninsular',
    fromRiver: 'Krishna',
    toRiver: 'Pennar',
    states: ['Andhra Pradesh'],
    path: 'M 340 500 Q 345 535 340 565',
    nodeFrom: { x: 340, y: 500, label: 'Nagarjunasagar' },
    nodeTo: { x: 340, y: 565, label: 'Somasila' },
    status: 'DPR Ready',
    lengthKm: 393,
    waterTransferBCM: 8.6,
    description: 'Enables bulk south-bound transit through Somasila dam to feed the lower Pennar and Tamil Nadu border.',
  },
  {
    id: 'pen-8',
    name: 'Pennar (Somasila)–Cauvery (Grand Anicut)',
    component: 'peninsular',
    fromRiver: 'Pennar',
    toRiver: 'Cauvery',
    states: ['Andhra Pradesh', 'Tamil Nadu'],
    path: 'M 340 565 Q 335 590 325 620',
    nodeFrom: { x: 340, y: 565, label: 'Somasila' },
    nodeTo: { x: 325, y: 620, label: 'Grand Anicut' },
    status: 'DPR Ready',
    lengthKm: 529,
    waterTransferBCM: 8.5,
    description: 'Crucial link supplying 8.5 BCM directly into Cauvery delta at ancient Grand Anicut and meeting Chennai drinking needs.',
  },
  {
    id: 'pen-9',
    name: 'Cauvery (Kattalai)–Vaigai–Gundar',
    component: 'peninsular',
    fromRiver: 'Cauvery',
    toRiver: 'Vaigai & Gundar',
    states: ['Tamil Nadu'],
    path: 'M 325 620 Q 320 645 315 670',
    nodeFrom: { x: 325, y: 620, label: 'Kattalai' },
    nodeTo: { x: 315, y: 670, label: 'Gundar' },
    status: 'In Progress',
    lengthKm: 255,
    waterTransferBCM: 2.2,
    description: 'Under active construction by Tamil Nadu government to extend irrigation across southern districts of Madurai and Ramanathapuram.',
  },
  {
    id: 'pen-10',
    name: 'Ken–Betwa Link',
    component: 'peninsular',
    fromRiver: 'Ken (Yamuna basin)',
    toRiver: 'Betwa (Yamuna basin)',
    states: ['Madhya Pradesh', 'Uttar Pradesh'],
    path: 'M 310 300 L 285 305',
    nodeFrom: { x: 310, y: 300, label: 'Daudhan Dam' },
    nodeTo: { x: 285, y: 305, label: 'Barua Sagar' },
    status: 'In Progress',
    lengthKm: 221,
    waterTransferBCM: 1.07,
    description: 'India’s pioneer national ILR project: transfers surplus Ken water via a 221 km concrete canal to drought-hit Bundelkhand.',
  },
  {
    id: 'pen-11',
    name: 'Parbati–Kalisindh–Chambal',
    component: 'peninsular',
    fromRiver: 'Parbati & Kalisindh',
    toRiver: 'Chambal',
    states: ['Madhya Pradesh', 'Rajasthan'],
    path: 'M 260 300 Q 250 315 240 330',
    nodeFrom: { x: 260, y: 300, label: 'Rana Pratap Sagar' },
    nodeTo: { x: 240, y: 330, label: 'Kota' },
    status: 'DPR Ready',
    lengthKm: 243,
    waterTransferBCM: 1.36,
    description: 'Tri-river link approved under the Modified PKC-ERCP framework for 13 eastern Rajasthan districts.',
  },
  {
    id: 'pen-12',
    name: 'Par–Tapi–Narmada',
    component: 'peninsular',
    fromRiver: 'Par & Tapi',
    toRiver: 'Narmada',
    states: ['Maharashtra', 'Gujarat'],
    path: 'M 225 390 Q 235 370 250 355',
    nodeFrom: { x: 225, y: 390, label: 'Jheri' },
    nodeTo: { x: 250, y: 355, label: 'Sardar Sarovar' },
    status: 'DPR Ready',
    lengthKm: 395,
    waterTransferBCM: 1.35,
    description: 'Transfers surplus west-flowing river yields from Western Ghats northwards into Sardar Sarovar feeder canals.',
  },
  {
    id: 'pen-13',
    name: 'Damanganga–Pinjal',
    component: 'peninsular',
    fromRiver: 'Damanganga',
    toRiver: 'Pinjal (Vaitarna basin)',
    states: ['Gujarat', 'Maharashtra'],
    path: 'M 215 410 L 210 430',
    nodeFrom: { x: 215, y: 410, label: 'Bhugad Dam' },
    nodeTo: { x: 210, y: 430, label: 'Pinjal Dam' },
    status: 'DPR Ready',
    lengthKm: 43,
    waterTransferBCM: 0.89,
    description: 'Dedicated drinking water conduit sending 895 million liters/day directly to Greater Mumbai municipal supply.',
  },
  {
    id: 'pen-14',
    name: 'Bedti–Varada',
    component: 'peninsular',
    fromRiver: 'Bedti',
    toRiver: 'Varada (Tungabhadra basin)',
    states: ['Karnataka'],
    path: 'M 225 520 L 245 525',
    nodeFrom: { x: 225, y: 520, label: 'Sirsi' },
    nodeTo: { x: 245, y: 525, label: 'Haveri' },
    status: 'Feasibility Done',
    lengthKm: 65,
    waterTransferBCM: 0.24,
    description: 'Diverts surplus west-flowing Arabian Sea discharges from Uttara Kannada inland to irrigate semi-arid Haveri.',
  },
  {
    id: 'pen-15',
    name: 'Netravati–Hemavati',
    component: 'peninsular',
    fromRiver: 'Netravati',
    toRiver: 'Hemavati (Cauvery basin)',
    states: ['Karnataka'],
    path: 'M 230 570 L 255 575',
    nodeFrom: { x: 230, y: 570, label: 'Sakleshpur' },
    nodeTo: { x: 255, y: 575, label: 'Gorur' },
    status: 'Under Investigation',
    lengthKm: 88,
    waterTransferBCM: 0.68,
    description: 'Lifts high-intensity monsoon discharges from coastal Western Ghats over the crest to feed Hemavati reservoir.',
  },
  {
    id: 'pen-16',
    name: 'Pamba–Achankovil–Vaippar',
    component: 'peninsular',
    fromRiver: 'Pamba & Achankovil',
    toRiver: 'Vaippar',
    states: ['Kerala', 'Tamil Nadu'],
    path: 'M 255 675 L 290 680',
    nodeFrom: { x: 255, y: 675, label: 'Punnamedu' },
    nodeTo: { x: 290, y: 680, label: 'Alagar Dam' },
    status: 'Feasibility Done',
    lengthKm: 51,
    waterTransferBCM: 0.63,
    description: 'Transfers unutilized surplus flows of Kerala rivers through tunnels across Western Ghats to drought-prone Tirunelveli.',
  },
];

// Combine all 30 links
export const ALL_ILR_LINKS: ILRLink[] = [...HIMALAYAN_LINKS, ...PENINSULAR_LINKS];

// Merits from BCV755B Syllabus Notes (All 18 points)
export const ILR_ALL_MERITS = [
  { id: 1, title: 'Uniform and economic water utilization', detail: 'Ensures scientific distribution of national water resources across deficient regions.' },
  { id: 2, title: 'Irrigation & power enhancement', detail: 'Adds ~35 Million Hectares of irrigated land and 34,000–40,000 MW hydro capacity.' },
  { id: 3, title: 'Ample domestic & industrial supply', detail: 'Provides sustainable drinking water to 116 drought-prone districts and urban centres.' },
  { id: 4, title: 'Inland navigation corridors', detail: '10,880 km of canal network enables low-carbon bulk cargo transport across river basins.' },
  { id: 5, title: 'Mitigation of drought & floods', detail: 'Protects 40 M Ha and 260M people from recurrent floods while safeguarding 86M from drought.' },
  { id: 6, title: 'Increases rural per capita income', detail: 'Stabilizes agrarian incomes by guaranteeing double-cropping and assured canal delivery.' },
  { id: 7, title: 'Reduces groundwater exploitation', detail: 'Replaces falling borewell extractions with clean, perennial gravity surface water.' },
  { id: 8, title: 'Massive employment generation', detail: 'Generates millions of technical, semi-skilled, and agricultural jobs across 14 states.' },
  { id: 9, title: 'Inland fisheries development', detail: 'Establishes vast freshwater aquaculture opportunities in link canals and reservoirs.' },
  { id: 10, title: 'Salinity control in coastal zones', detail: 'Sustained freshwater discharge pushes back saline marine intrusion in coastal aquifers.' },
  { id: 11, title: 'Recreation & eco-tourism facilities', detail: 'Reservoirs, reservoirs parks, and green corridors create scenic recreational spaces.' },
  { id: 12, title: 'Surrounding infrastructure development', detail: 'Drives roads, rural electrification, bridges, and market connectivity along canal paths.' },
  { id: 13, title: 'Socio-economic growth of backward regions', detail: 'Transforms chronically deprived drylands like Bundelkhand, Rayalaseema, and Vidarbha.' },
  { id: 14, title: 'Artificial groundwater recharge', detail: 'Percolation from unlined reservoirs and canals steadily elevates regional water tables.' },
  { id: 15, title: 'Halts distressed distress migration', detail: 'Stops seasonal mass migration of rural labor to overcrowded metro slums.' },
  { id: 16, title: 'Converts barren land to cultivable fields', detail: 'Reclaims vast arid wastelands into productive food-grain and pulse cultivation.' },
  { id: 17, title: 'Reduces coastal siltation and deltas', detail: 'Regulates sediment flows, minimizing runaway delta formation and marine silt accumulation.' },
  { id: 18, title: 'Substantial savings on relief expenditure', detail: 'Saves the Government over ₹1,200 crore annually in recurring flood and drought relief.' },
];

// Demerits / Concerns from BCV755B Syllabus Notes (All 14 points)
export const ILR_ALL_DEMERITS = [
  { id: 1, title: 'Submersion of land & displacement', detail: 'Construction of 60 major reservoirs submerges fertile valleys and displaces indigenous communities.' },
  { id: 2, title: 'Ecological & biodiversity disruption', detail: 'Severing river flows affects downstream estuarine ecology, fish migrations, and wildlife habitats (e.g. Panna Tiger Reserve).' },
  { id: 3, title: 'Interstate & international water disputes', detail: 'Riparian states contest surplus definitions; international concerns with Bangladesh, Nepal, and Bhutan.' },
  { id: 4, title: 'Legal & constitutional hurdles', detail: 'Water is fundamentally a State Subject (List II), necessitating complex interstate water agreements.' },
  { id: 5, title: 'Astronomical capital & maintenance costs', detail: 'Initial estimate of ₹5,60,000 crores (2002) has escalated dramatically with ongoing maintenance demands.' },
  { id: 6, title: 'Water pollution in conveyance', detail: 'Open-channel canals traversing industrial and urban stretches risk severe chemical and sewage contamination.' },
  { id: 7, title: 'Conveyance losses (seepage & evaporation)', detail: 'High tropical temperatures cause intense evaporation losses, alongside seepage across porous reaches.' },
  { id: 8, title: 'Complex land acquisition & rehabilitation', detail: 'Resettlement of lakhs of rural families faces severe administrative friction and community protests.' },
  { id: 9, title: 'Mandatory compensatory afforestation', detail: 'Submergence of deciduous and evergreen forests demands massive afforestation drives that take decades to mature.' },
  { id: 10, title: 'Decadal implementation timeframe (40 years)', detail: 'Extended timeline subjects project models to climate volatility, inflation, and shifting hydrologic baselines.' },
  { id: 11, title: 'High pumping power in elevated terrain', detail: 'Lifting water across Western Ghats and Deccan escarpments consumes vast electrical energy.' },
  { id: 12, title: 'Need for extensive public & political consensus', detail: 'Requires protracted consensus building across multiple political parties, civil society, and environmental activists.' },
  { id: 13, title: 'Soil erosion and canal sedimentation', detail: 'Heavy silt loads in Himalayan rivers can rapidly choke storage reservoirs and reduce live capacities.' },
  { id: 14, title: 'Numerous cross-drainage structures required', detail: 'Traversing undulating terrain requires thousands of expensive aqueducts, super-passages, and siphons.' },
];
