import type { ModuleContent } from './types';

const air: ModuleContent = {
  id: 3,
  slug: 'air',
  name: 'Air',
  shortName: 'AIR',
  tagline: 'The thin shell we breathe.',
  subtitle: 'Measure what surrounds us, then trace how cleaner air is made.',
  accent: '#9FB8C4',
  image: '/images/world-air.webp',
  noteFile: '/notes/module-03-air.md',
  noteLabel: 'Module 03 · Air study notes',
  next: { slug: 'biodiversity', name: 'Biodiversity & Ecosystem' },
  chapters: [
    { id: 'ch-01', part: 'PART 01', title: 'A thin atmospheric envelope', deck: 'Dry air is mostly three gases. The troposphere is the lowest atmospheric layer and holds nearly all water vapour.', kind: 'air-composition', facts: [{ label: 'Nitrogen', value: '78.084%' }, { label: 'Oxygen', value: '20.946%' }, { label: 'Argon', value: '0.934%' }, { label: 'Troposphere', value: '~12 km · ~80% of atmospheric mass' }], bullets: ['The course notes describe air as a non-homogeneous mixture of gases.', 'Nitrogen, oxygen and argon make up about 99% of dry air.', 'Trace gases include carbon dioxide, neon, helium and methane; water vapour varies.'] },
    { id: 'ch-02', part: 'PART 02', title: 'When air becomes polluted', deck: 'Pollution may be gaseous, or carried as solid and liquid particles suspended in air.', kind: 'air-pollution', facts: [{ label: 'Forms', value: 'Gases · solid aerosols · liquid aerosols' }, { label: 'Aerosol', value: 'A solid or liquid particle suspended in air' }], bullets: ['The notes define air pollution as contaminants in air that can harm people, animals, plants or property.', 'Pollutants may be natural or anthropogenic (human-caused).', 'Natural examples include volcanic ash, sea salt, pollen, smoke and windblown dust.'] },
    { id: 'ch-03', part: 'PART 03', title: 'Classify the pollutant', deck: 'Change the lens: pollutants regroup by origin, physical state, source or emission location.', kind: 'pollutant-classifier', facts: [{ label: 'Primary', value: 'Emitted directly' }, { label: 'Secondary', value: 'Formed through atmospheric reactions' }], bullets: ['By origin: primary or secondary.', 'By state: gaseous or particulate.', 'By source: natural or man-made.', 'By location: stationary sources, including point and area sources.'] },
    { id: 'ch-04', part: 'PART 04', title: 'A standard for ambient air', deck: 'The supplied notes present the 2009 NAAQS values notified by CPCB under the Air Act, 1981.', kind: 'naaqs', facts: [{ label: 'PM₂.₅ · annual', value: '40 μg/m³' }, { label: 'PM₂.₅ · 24 hours', value: '60 μg/m³' }, { label: 'PM₁₀ · annual', value: '60 μg/m³' }, { label: 'O₃ · 8 hours', value: '100 μg/m³' }], bullets: ['NAAQS provide a common yardstick for monitoring and assessing outdoor air quality.', 'The notes list different SO₂ and NO₂ annual limits for ecologically sensitive areas.', 'Annual compliance is based on repeated measurements; the supplied notes specify a minimum of 104 readings.'] },
    { id: 'ch-05', part: 'PART 05', title: 'One number, a public signal', deck: 'Set an AQI value. The dial updates its category and the health message.', kind: 'aqi-gauge', facts: [{ label: 'Scale in notes', value: '0–500' }, { label: 'Categories', value: '6' }, { label: 'Basis', value: 'Worst sub-index across 8 pollutants' }], bullets: ['The AQI communicates complex air-quality data using a number, a category and a colour.', 'The notes describe sub-indices for PM₁₀, PM₂.₅, NO₂, SO₂, CO, O₃, NH₃ and lead.', 'Course breakpoint bands: 0–50 Good; 51–100 Satisfactory; 101–200 Moderate; 201–300 Poor; 301–400 Very Poor; 401–500 Severe.'] },
    { id: 'ch-06', part: 'PART 06', title: 'From pollutant to body', deck: 'Choose a pollutant to highlight the systems it can affect. SPM receives a closer look.', kind: 'body-map', facts: [{ label: 'Pollutants covered', value: '11 groups in the notes' }, { label: 'Special focus', value: 'Suspended particulate matter (SPM)' }], bullets: ['The notes cover tobacco smoke, biological pollutants, VOCs, formaldehyde, lead, radon, ground-level ozone, NOₓ, CO, SO₂ and SPM.', 'Effects vary by pollutant, concentration, exposure duration and individual sensitivity.', 'The SPM deep-dive in the notes emphasizes particles reaching the respiratory system.'] },
    { id: 'ch-07', part: 'PART 07', title: 'The cost of dirty air', deck: 'Air pollution damages health, materials, vegetation and heritage — costs that rarely appear on a product label.', kind: 'economic-effects', facts: [{ label: 'Healthcare costs · 2015', value: 'USD 21 billion' }, { label: 'Projected · 2060', value: 'USD 176 billion' }, { label: 'Premature deaths · 2060 projection', value: '6–9 million / year' }], bullets: ['The notes report projections for healthcare costs, lost work days and welfare costs.', 'SOₓ and moisture can damage limestone; ozone affects rubber; pollutants also damage textiles, leather, paper and electronics.', 'The notes identify monuments including the Taj Mahal and Channakeshava Temple among heritage affected by air pollution.'] },
    { id: 'ch-08', part: 'PART 08', title: 'Capture it before it escapes', deck: 'Choose a control device to see how particles or gases are removed from industrial exhaust.', kind: 'control-equipment', facts: [{ label: 'Particulate control', value: 'ESP · cyclone · fabric filter' }, { label: 'Gas control', value: 'Scrubber · incineration · carbon capture' }], bullets: ['Electrostatic precipitators charge particles so they collect on plates.', 'Cyclone separators use spinning gas flow to separate particles; fabric filters trap them in filter media.', 'Scrubbers, incineration and carbon capture target gaseous emissions through different mechanisms.'] },
    { id: 'ch-09', part: 'PART 09', title: 'Thin the smoke plume', deck: 'Apply control measures and watch the plume change.', kind: 'smoke-control', facts: [{ label: 'Smoke', value: 'A mixture of fine solid, liquid and gas particles' }], bullets: ['Smoke is an aerosol released during combustion.', 'The notes list ESPs, cyclone separators, scrubbers and fabric filters as control devices.', 'Cleaner fuels, better combustion, vehicle catalytic converters and routine inspection also help control smoke.'] },
    { id: 'ch-10', part: 'PART 10', title: 'A shield in the stratosphere', deck: 'Scrub through the sequence: CFCs reach the stratosphere, UV releases chlorine, and chlorine participates in ozone-destroying cycles.', kind: 'ozone', facts: [{ label: 'Ozone layer altitude in notes', value: '~24 km' }, { label: 'Typical column', value: '~300 DU' }, { label: 'Montreal Protocol', value: '1987' }], bullets: ['The ozone layer absorbs short-wavelength ultraviolet radiation.', 'The notes describe chlorine released from CFCs as a catalyst in ozone destruction.', 'The Montreal Protocol (1987) committed nations to reduce ozone-depleting substances; the notes discuss recovery if these substances are phased out.'] },
    { id: 'ch-11', part: 'PART 11', title: 'Sunlight changes the chemistry', deck: 'In the troposphere, sunlight helps NOₓ and hydrocarbons form ground-level ozone and photochemical smog.', kind: 'photochemical', facts: [{ label: 'Key ingredients', value: 'Sunlight · NOₓ · hydrocarbons / VOCs' }, { label: 'Products in notes', value: 'O₃ · PAN · photochemical smog' }], bullets: ['NO₂ + sunlight can produce NO and atomic oxygen; atomic oxygen reacts with O₂ to form ozone.', 'Ground-level ozone and hydrocarbons can form PAN and other harmful compounds.', 'The notes distinguish harmful tropospheric smog from stratospheric ozone depletion.'] },
  ],
  recap: [{ label: 'Dry-air nitrogen', value: '78.084%' }, { label: 'Dry-air oxygen', value: '20.946%' }, { label: 'Troposphere', value: '~12 km' }, { label: 'Montreal Protocol', value: '1987' }],
};
export default air;
