import type { ModuleContent } from './types';

const biodiversity: ModuleContent = {
  id: 4,
  slug: 'biodiversity',
  name: 'Biodiversity & Ecosystem',
  shortName: 'BIODIVERSITY',
  tagline: 'The web of living things.',
  subtitle: 'Zoom from genes to ecosystems — and see what keeps the web intact.',
  accent: '#6FA96B',
  image: '/images/world-bio.webp',
  noteFile: '/notes/module-04-biodiversity.md',
  noteLabel: 'Module 04 · Biodiversity study notes',
  next: { slug: 'warming', name: 'Global Warming & EIA' },
  chapters: [
    { id: 'ch-01', part: 'PART 01', title: 'The variety of life', deck: 'Biodiversity describes variation in genes, species and ecosystems across the biosphere.', kind: 'biodiversity-intro', facts: [{ label: 'Flora', value: 'Plant life' }, { label: 'Fauna', value: 'Animal life' }, { label: 'Together with microbes', value: 'Biological diversity' }], bullets: ['The notes define biodiversity as the degree of nature’s variety in the biosphere.', 'It includes terrestrial and aquatic ecosystems, and the living things within them.', 'Flora, fauna and microorganisms together form biological diversity.'] },
    { id: 'ch-02', part: 'PART 02', title: 'Three scales of diversity', deck: 'Move from genetic variation to species richness and whole ecosystems.', kind: 'life-scale', facts: [{ label: 'Identified / categorized', value: '~1.8 million species' }, { label: 'Estimated terrestrial species', value: '~8.7 million' }, { label: 'India', value: 'Among 15 species-rich nations' }], bullets: ['Genetic diversity is variation within a species; the notes call wild-species diversity a gene pool.', 'Species diversity includes both the number of species and their relative abundance.', 'Ecosystem diversity describes variety at ecosystem level, including natural and modified systems.', 'Estimates in the supplied notes: ~2.2M oceanic species; 10–30M insects; 5–10M bacteria; 1.5–3M fungi; ~220,000 vascular plants.'] },
    { id: 'ch-03', part: 'PART 03', title: 'Six values of biodiversity', deck: 'Choose a value. Each one reveals a different relationship between people and the living world.', kind: 'biodiversity-values', facts: [{ label: 'Values', value: 'Consumptive · productive · social · ethical · aesthetic · option' }], bullets: ['Consumptive value: resources directly used, including food, fuelwood and medicinal plants.', 'Productive value: biological products with commercial value.', 'The remaining values recognize social and cultural connections, the right of species to exist, beauty and potential future uses.'] },
    { id: 'ch-04', part: 'PART 04', title: 'Six pressures on the web', deck: 'Toggle threats to see habitat quality and the species index respond; restore the scene with solutions.', kind: 'threats', facts: [{ label: 'Threats in notes', value: '6' }, { label: 'Example', value: 'Water hyacinth as an introduced species' }], bullets: ['Habitat loss · overpopulation · environmental pollution · climate change · exotic species · overuse of vegetation.', 'Introduced species may spread disease, compete with or prey on native species, hybridize or alter habitats.', 'The notes recommend protecting intact habitat, public education, planting trees and reducing harmful expansion.'] },
    { id: 'ch-05', part: 'PART 05', title: 'Conserve where possible — protect where needed', deck: 'Compare in-situ conservation with ex-situ methods, then open a method card.', kind: 'conservation', facts: [{ label: 'In-situ', value: 'Conservation in a species’ natural habitat' }, { label: 'Ex-situ', value: 'Conservation under controlled or off-site conditions' }], bullets: ['In-situ examples: biosphere reserves, national parks, wildlife sanctuaries and on-farm conservation.', 'Ex-situ examples: zoos, captive breeding, seed or gene banks, pollen culture and reproductive technologies.', 'Other methods in the notes include ecological restoration and social forestry.'] },
    { id: 'ch-06', part: 'PART 06', title: 'An ecosystem is a working whole', deck: 'Switch between living and non-living components, then trace energy through the system.', kind: 'ecosystem-components', facts: [{ label: 'Biotic', value: 'Producers · consumers · decomposers' }, { label: 'Abiotic', value: 'Sunlight · water · soil · air · temperature' }], bullets: ['An ecosystem includes interacting communities of organisms and their physical environment.', 'Producers capture energy; consumers feed through trophic levels; decomposers return nutrients.', 'The notes describe energy transfer through food chains and cycling of materials through ecosystems.'] },
    { id: 'ch-07', part: 'PART 07', title: 'Enter a biome', deck: 'Choose an ecosystem. Aquatic scenes include the zones of a lake.', kind: 'biome-explorer', facts: [{ label: 'Ecosystem types', value: 'Forest · desert · grassland · aquatic · estuarine · wetland' }, { label: 'Lake zones', value: 'Littoral · limnetic · profundal' }], bullets: ['Forest, desert and grassland ecosystems have distinct structure and function.', 'Aquatic systems include freshwater, lentic lakes and ponds, and marine or ocean ecosystems.', 'Estuaries mix river and sea influences; wetlands are biologically diverse and help purify water, control floods and store carbon.'] },
    { id: 'ch-08', part: 'PART 08', title: 'Cycles that hold systems together', deck: 'Switch cycles. Follow the movement of matter through living and non-living parts of the ecosystem.', kind: 'biogeochemical-cycles', facts: [{ label: 'Cycles in notes', value: 'Carbon · nitrogen · phosphorus · water' }, { label: 'Food-chain transfer', value: '~10% of energy per trophic level (notes)' }], bullets: ['Biogeochemical cycling moves elements through biotic and abiotic components.', 'Biodiversity contributes through processes such as nitrogen fixation, photosynthesis, respiration, decomposition and transpiration.', 'The notes also describe biomagnification: some toxic substances become more concentrated at higher trophic levels.'] },
    { id: 'ch-09', part: 'PART 09', title: 'From plant diversity to medicines and food', deck: 'Explore a few plant–drug examples, then the role of biodiversity in fisheries.', kind: 'medicinal-fisheries', facts: [{ label: 'Medicines in notes', value: '~70% derived from plants / plant extracts' }, { label: 'Freshwater fish', value: '41% of known global fish species' }], bullets: ['The supplied notes pair quinine with Cinchona bark, morphine with opium poppy, Taxol with yew and aspirin with willow bark.', 'Freshwater and marine biodiversity support fisheries, food security and coastal livelihoods.', 'Loss of species can disrupt food webs on which healthy fish populations depend.'] },
  ],
  recap: [{ label: 'Levels', value: '3' }, { label: 'Values', value: '6' }, { label: 'Threats', value: '6' }, { label: 'Estimated terrestrial species', value: '~8.7M' }],
};
export default biodiversity;
