import type { ModuleContent } from './types';

const land: ModuleContent = {
  id: 1,
  slug: 'land',
  name: 'Land',
  shortName: 'LAND',
  tagline: 'The ground beneath everything.',
  subtitle: 'From a molten planet to the soil that feeds us.',
  accent: '#C9A15A',
  image: '/images/world-land.webp',
  noteFile: '/notes/module-01-land.md',
  noteLabel: 'Module 01 · Land study notes',
  next: { slug: 'water', name: 'Water' },
  chapters: [
    { id: 'ch-01', part: 'PART 01', title: 'Earth, at the beginning', deck: 'A hot, young planet cooled into the home we know.', kind: 'formation', facts: [{ label: 'Age of Earth', value: '4.6 billion years' }, { label: 'Major layers', value: '4' }], bullets: ['Early Earth was described in the notes as a hot ball of fire and gas.', 'As the surface cooled, it hardened into rock while the interior remained molten.', 'Water collecting in low-lying areas helped form seas and oceans.'] },
    { id: 'ch-02', part: 'PART 01', title: 'A planet in layers', deck: 'Select a layer. Drag the globe to turn it; open the cutaway to see the interior.', kind: 'earth-layers', facts: [{ label: 'Crust', value: '<1% of Earth’s volume' }, { label: 'Mantle', value: '~2,900 km' }, { label: 'Outer core', value: '~2,400 km thick' }, { label: 'Inner core', value: '~1,220 km radius · ~5,000°C' }], bullets: ['The crust is the thin, solid outer shell and part of the lithosphere.', 'The mantle is made largely of silicate material; the notes describe tectonic plates moving over it.', 'The outer core is fluid and mainly iron and nickel; the inner core is solid.'] },
    { id: 'ch-03', part: 'PART 01', title: 'How the crust took shape', deck: 'Cooling, water and tectonic movement continually reshape the surface.', kind: 'tectonics', facts: [{ label: 'Sequence', value: 'Cool → harden → move' }], bullets: ['A hardened outer surface created the early land forms.', 'Precipitation accelerated the shaping of the crust.', 'Tectonic plates moved over geological time; their movement helped form the continents.'] },
    { id: 'ch-04', part: 'PART 02', title: 'Land is a resource', deck: 'Land is both the platform for life and a source of materials.', kind: 'land-cover', facts: [{ label: 'Earth’s surface', value: '20% land' }, { label: 'Land includes', value: 'Forests · wetlands · grasslands · farms · settlements' }], bullets: ['Land is a major constituent of the life-supporting lithosphere.', 'The notes describe land as roughly one-fifth of Earth’s surface.', 'Its cover ranges from natural ecosystems to agricultural land and human settlements.'] },
    { id: 'ch-05', part: 'PARTS 02 & 07', title: 'Soil is a living layer', deck: 'Soil forms slowly through weathering and the maturation of organic matter.', kind: 'soil-profile', facts: [{ label: 'Weathering', value: 'Rock → particles' }, { label: 'Pedogenesis', value: 'Soil matures; humus develops' }, { label: 'Formation time', value: 'Decades to centuries' }], bullets: ['Soil is the upper weathered crust that supports plant growth.', 'Plants draw water and mineral nutrients from soil; many detritus organisms live there.', 'Pedology is the study of soil origin, formation and distribution.'] },
    { id: 'ch-06', part: 'PART 03', title: 'Landforms, many habitats', deck: 'Choose a landscape to see what makes it distinct.', kind: 'landforms', facts: [{ label: 'Grasslands', value: 'Up to 40% of terrestrial surface' }, { label: 'Wetlands', value: 'Purify · store · cycle nutrients' }], bullets: ['Grasslands occur on every continent except Antarctica and are sensitive to climate variability.', 'Wetlands may be permanently or seasonally flooded and support adapted vegetation.', 'Forests, farmland, tundra, deserts and urban settlements each have different ecological roles.'] },
    { id: 'ch-07', part: 'PART 04', title: 'Conserve the land base', deck: 'Protection is not about freezing landscapes in time. It is about using land wisely while keeping its natural processes intact.', kind: 'definition', quote: 'Protect the land’s form, soil and living processes — and leave room for nature to continue.', facts: [{ label: 'Conservation means', value: 'Protection + wise use' }], bullets: ['Minimize disruption to natural forms and ecological processes.', 'Protect biophysical features, endangered species and traditional practices.', 'Keep meaningful areas open and resilient.'] },
    { id: 'ch-08', part: 'PART 05', title: 'When forest becomes elsewhere', deck: 'Move the reveal to compare a living canopy with cleared land. The definition in the notes also includes long-term loss of canopy cover.', kind: 'forest-slider', facts: [{ label: 'FAO definition in notes', value: 'Canopy cover below 10%' }, { label: 'Related ideas', value: 'Degradation · fragmentation' }], bullets: ['Deforestation is conversion of forest to another land use, such as agriculture or urban use.', 'Forest degradation reduces forest quality, density or structure; fragmentation breaks continuous forest into patches.', 'Afforestation creates forest on land not recently forested; reforestation re-establishes forest cover.'] },
    { id: 'ch-09', part: 'PART 06', title: 'Land use leaves a footprint', deck: 'Land-use change can alter water, habitat, livelihoods and the shape of the landscape.', kind: 'land-use', facts: [{ label: 'Case study', value: 'Shire River · Malawi' }, { label: 'Compare', value: 'Natural · agricultural · developed' }], bullets: ['Land use describes how people use land directly and indirectly.', 'Development can seal soil and fragment habitat; agriculture can change erosion, nutrients and water quality.', 'The supplied notes use the Shire River in Malawi to examine land-use impacts.'] },
    { id: 'ch-10', part: 'PARTS 07–09', title: 'A healthy soil profile', deck: 'Soil is a mix of mineral particles, air, water and organic matter — and its health has physical, chemical and biological dimensions.', kind: 'soil-health', facts: [{ label: 'Mineral particles', value: '45%' }, { label: 'Air', value: '25%' }, { label: 'Water', value: '25%' }, { label: 'Organic matter', value: '5%' }], bullets: ['The notes identify texture, compaction, nutrients, pH, salinity, organic matter and microbial activity as soil-health indicators.', 'Organic matter improves structure and water retention, reduces erosion and releases nutrients slowly.', 'Soil filters water, supports food and biomass production, stores carbon and provides habitat.'] },
    { id: 'ch-11', part: 'PARTS 10 & 12', title: 'Six pathways to degradation', deck: 'Select a cause to see how it can weaken land and food systems.', kind: 'degradation', facts: [{ label: 'Main causes', value: '6' }, { label: 'India', value: '2.4% of world land area · 18% of population (notes)' }], bullets: ['Erosion · fertility depletion · landslides · soil sealing · contamination · salination.', 'Soil erosion and salinification can reduce productivity and raise management costs.', 'The notes connect land degradation with crop losses, livelihoods and food security in India and Sub-Saharan Africa.'] },
    { id: 'ch-12', part: 'PART 11', title: 'Keep soil in place', deck: 'Turn conservation practices on. Each changes the farm hillside in a different way.', kind: 'soil-conservation', facts: [{ label: 'Strategies', value: '8 practical approaches' }], bullets: ['Reduce soil disturbance; rotate crops; keep soil covered.', 'Diversify production; add organic amendments; integrate livestock thoughtfully.', 'Use terrace farming and shelter belts where appropriate.'] },
    { id: 'ch-13', part: 'PART 13', title: 'Plan for the long view', deck: 'Sustainable land-use planning matches land capability with human needs while safeguarding resources for the future.', kind: 'land-planning', facts: [{ label: 'Land, over time', value: 'Wealth → commodity → scarce resource → community resource' }], bullets: ['Assess land and water potential, alternatives, and economic and social conditions.', 'Protect productive land, groundwater, habitats, ecological corridors and floodplains.', 'Planning can be spatial, participatory, ecosystem-based, regional, integrated or urban.'] },
  ],
  recap: [{ label: 'Earth formed', value: '4.6 billion years ago' }, { label: 'Land surface', value: '20%' }, { label: 'Soil formation', value: 'Decades to centuries' }, { label: 'Soil conservation', value: '8 strategies' }],
};
export default land;
