export type QuizQuestion = {
  id?: string;
  module: string;
  topic?: string;
  difficulty?: 'Standard' | 'Advanced' | 'Expert';
  sectionId?: string;
  prompt: string;
  choices: string[];
  answer: number;
  explanation: string;
  takeaway?: string;
};

export const quizQuestions: QuizQuestion[] = [
  // ==========================================
  // MODULE 01: LAND (15 Comprehensive Questions)
  // ==========================================
  {
    id: 'land-q01',
    module: 'land',
    sectionId: 'ch-formation',
    topic: 'Cosmic Accretion & Earth Formation',
    difficulty: 'Standard',
    prompt: 'According to planetary accretion records, approximately how long ago did the Earth form?',
    choices: [
      '4.6 million years ago',
      '4.6 billion years ago',
      '46 billion years ago',
      '460 million years ago',
    ],
    answer: 1,
    explanation: 'The Earth formed approximately 4.6 billion years ago (4,600 Ma) from gravitational accretion of cosmic dust, meteorites, and planetesimals within the solar nebula.',
    takeaway: 'Earth is 4.6 billion years old, undergoing early core differentiation and atmospheric degassing.',
  },
  {
    id: 'land-q02',
    module: 'land',
    sectionId: 'ch-layers',
    topic: 'Earth Internal Structure',
    difficulty: 'Advanced',
    prompt: 'Which mechanical layer of Earth is composed of semi-fluid, plastic rock upon which the rigid lithospheric plates drift?',
    choices: [
      'Lithosphere',
      'Asthenosphere',
      'Outer Core',
      'Inner Core',
    ],
    answer: 1,
    explanation: 'The asthenosphere is the ductile, semi-fluid upper mantle layer (~100 to 660 km deep) whose thermal convection currents drive continental drift and tectonic activity.',
    takeaway: 'The rigid lithosphere floats and drifts across the plastic, convecting asthenosphere.',
  },
  {
    id: 'land-q03',
    module: 'land',
    sectionId: 'ch-continents',
    topic: 'Plate Tectonics & Continental Drift',
    difficulty: 'Standard',
    prompt: 'What was the name of the unified supercontinent that existed ~250 million years ago before rifting into Laurasia and Gondwanaland?',
    choices: [
      'Rodinia',
      'Pangaea',
      'Panthalassa',
      'Columbia',
    ],
    answer: 1,
    explanation: 'Alfred Wegener proposed that ~250 million years ago, all landmasses coalesced into the supercontinent Pangaea, encircled by the vast Panthalassa ocean, before breaking apart.',
    takeaway: 'Pangaea rifted apart via tectonic movement to form our modern continents.',
  },
  {
    id: 'land-q04',
    module: 'land',
    sectionId: 'ch-resource',
    topic: 'Planetary Land Allocation',
    difficulty: 'Standard',
    prompt: 'What percentage of the Earth’s total surface area is land, and approximately how much of that land is directly habitable?',
    choices: [
      '29% land surface, of which ~71% is habitable',
      '50% land surface, of which ~90% is habitable',
      '20% land surface, of which ~50% is habitable',
      '71% land surface, of which ~29% is habitable',
    ],
    answer: 0,
    explanation: 'Land covers roughly 29.2% of Earth (149 million km²), with oceans covering 70.8%. Of this total land area, approximately 71% is habitable, while 29% comprises glaciers, barren deserts, and high peaks.',
    takeaway: 'Habitable land is a strictly finite planetary boundary supporting 8+ billion people.',
  },
  {
    id: 'land-q05',
    module: 'land',
    sectionId: 'ch-soil',
    topic: 'Soil Formation (Pedogenesis)',
    difficulty: 'Advanced',
    prompt: 'What is the fundamental scientific difference between weathering and pedogenesis?',
    choices: [
      'Weathering produces organic humus; pedogenesis only crushes boulders',
      'Weathering breaks parent rock into mineral fragments; pedogenesis is the maturation of true soil with humus and horizons',
      'Weathering occurs only in tropical climates; pedogenesis occurs exclusively in polar ice caps',
      'There is no distinction; they are synonymous terms in earth science',
    ],
    answer: 1,
    explanation: 'Weathering (physical, chemical, biological) disintegrates solid bedrock into mineral regolith. Pedogenesis is the multi-generational biochemical process that develops distinct soil horizons and incorporates organic humus.',
    takeaway: 'Soil = Weathered Mineral Parent Material + Biological Pedogenesis over centuries.',
  },
  {
    id: 'land-q06',
    module: 'land',
    sectionId: 'ch-soil',
    topic: 'Soil Horizons Profile',
    difficulty: 'Advanced',
    prompt: 'In a mature soil profile, which master horizon is known as the zone of eluviation (maximum leaching of clay, iron, and minerals)?',
    choices: [
      'O Horizon (Organic humus layer)',
      'A Horizon (Topsoil)',
      'E Horizon (Eluviated leached layer)',
      'C Horizon (Parent rock regolith)',
    ],
    answer: 2,
    explanation: 'The E horizon (from French "éluvier" = to wash out) is a heavily leached layer occurring below the A horizon, where downward percolating water removes clays, iron, and organic acids, leaving bleached silicates.',
    takeaway: 'The E Horizon is the zone of eluviation; the underlying B Horizon is the zone of illuviation (accumulation).',
  },
  {
    id: 'land-q07',
    module: 'land',
    sectionId: 'ch-landforms',
    topic: 'Geomorphology & Landforms',
    difficulty: 'Standard',
    prompt: 'Which topographic feature distinguishes a plateau from a mountain range?',
    choices: [
      'Plateaus are created solely by coral reef deposition',
      'Plateaus have an elevated, relatively level tableland summit bounded by steep escarpments',
      'Mountains are always lower in elevation than surrounding plains',
      'Plateaus are characterized by sharply pointed volcanic peaks',
    ],
    answer: 1,
    explanation: 'A plateau is an elevated landform with a relatively flat top (tableland) that rises sharply above adjacent plains on at least one side (e.g., the Deccan Plateau, Colorado Plateau).',
    takeaway: 'Plateaus feature expansive elevated flat summits, whereas mountains have steep gradients and sharp summits.',
  },
  {
    id: 'land-q08',
    module: 'land',
    sectionId: 'ch-conservation',
    topic: 'Landform Conservation',
    difficulty: 'Standard',
    prompt: 'Which landscape conservation strategy maintains gene flow and animal migration across fragmented natural landforms?',
    choices: [
      'Ecological Wildlife Corridors & Habitat Linkages',
      'Perimeter clear-cutting of buffer zones',
      'Complete monoculture pine planting',
      'Fencing off every mountain ridge with concrete walls',
    ],
    answer: 0,
    explanation: 'Ecological corridors connect isolated forest patches and mountain ridges, allowing large mammals, pollinators, and seeds to migrate safely, preventing genetic isolation and local extinctions.',
    takeaway: 'Corridors counteract habitat fragmentation by maintaining continuous ecological connectivity.',
  },
  {
    id: 'land-q09',
    module: 'land',
    sectionId: 'ch-deforestation',
    topic: 'Deforestation & Forest Ecology',
    difficulty: 'Standard',
    prompt: 'Globally, what single human activity is recognized by the FAO as the primary driver of tropical deforestation?',
    choices: [
      'Commercial agriculture (cattle ranching, soybean cultivation, and oil palm plantations)',
      'Construction of rural single-family housing',
      'Underground geothermal energy wells',
      'Urban park development',
    ],
    answer: 0,
    explanation: 'Commercial agriculture accounts for approximately 73% of tropical deforestation, driven primarily by cattle ranching (beef) in South America and oil palm/soy cultivation in Southeast Asia and the Amazon.',
    takeaway: 'Agricultural commodity expansion is the single greatest driver of worldwide forest clearing.',
  },
  {
    id: 'land-q10',
    module: 'land',
    sectionId: 'ch-landuse',
    topic: 'Land-Use Change & Hydrology',
    difficulty: 'Expert',
    prompt: 'In the Shire River Basin case study, what was the direct downstream consequence of upstream deforestation and steep hillside farming?',
    choices: [
      'The river completely evaporated within three weeks',
      'Massive sediment loading and siltation that choked hydroelectric turbine intakes at Nkula and Tedzani',
      'Sudden freezing of the lower wetlands into glacier ice',
      'Transformation of the river bed into solid volcanic basalt',
    ],
    answer: 1,
    explanation: 'Deforestation and uncontrolled slope cultivation in the upper Shire catchment caused catastrophic topsoil erosion. Torrential rains carried hundreds of thousands of tons of sediment into the river, choking cooling water and turbine intakes at Nkula and Tedzani power plants, triggering nationwide blackouts in Malawi.',
    takeaway: 'Watershed deforestation directly threatens downstream clean energy, reservoir storage, and municipal water security.',
  },
  {
    id: 'land-q11',
    module: 'land',
    sectionId: 'ch-soilhealth',
    topic: 'Soil Health & Composition',
    difficulty: 'Standard',
    prompt: 'What is the volumetric breakdown of an ideal, healthy agricultural soil matrix?',
    choices: [
      '45% Mineral particles, 25% Air, 25% Water, 5% Organic matter',
      '70% Mineral particles, 10% Air, 10% Water, 10% Organic matter',
      '30% Mineral particles, 35% Air, 30% Water, 5% Organic matter',
      '50% Mineral particles, 40% Air, 5% Water, 5% Organic matter',
    ],
    answer: 0,
    explanation: 'An optimal agricultural soil profile comprises 45% mineral solids (sand, silt, clay), 50% pore space evenly divided between 25% air and 25% water, and 5% organic matter (80% humus, 10% roots, 10% active soil organisms).',
    takeaway: 'The 45-25-25-5 balance ensures root aeration, adequate water retention, and microbial nutrient cycling.',
  },
  {
    id: 'land-q12',
    module: 'land',
    sectionId: 'ch-degradation',
    topic: 'Land Degradation Pathways',
    difficulty: 'Advanced',
    prompt: 'How does excessive furrow irrigation in arid climates cause severe secondary soil salinization?',
    choices: [
      'By freezing the soil profile below the root zone',
      'Capillary draw pulls dissolved mineral salts upward as rapid surface evaporation leaves salt crusts behind',
      'By leaching all mineral salts into the lower mantle',
      'By permanently converting clay minerals into pure silica sand',
    ],
    answer: 1,
    explanation: 'Over-irrigation in arid regions raises groundwater tables. In intense heat, water evaporates quickly from the surface, causing upward capillary suction that brings dissolved sodium, calcium, and magnesium salts to the topsoil, where they crystallize into toxic saline crusts.',
    takeaway: 'Capillary action coupled with rapid evaporation drives agricultural salinization in drylands.',
  },
  {
    id: 'land-q13',
    module: 'land',
    sectionId: 'ch-soilconservation',
    topic: 'Soil Conservation Strategies',
    difficulty: 'Standard',
    prompt: 'Which soil conservation strategy involves plowing and planting crops along lines of equal elevation across a slope?',
    choices: [
      'Contour Farming (Contour Plowing)',
      'Vertical furrowing directly down the hillside',
      'Continuous stubble burning',
      'Deep subsoil bedrock blasting',
    ],
    answer: 0,
    explanation: 'Contour farming follows natural elevation contours, creating horizontal ridges that act as micro-terraces, trapping runoff, allowing infiltration, and reducing soil erosion by up to 50% compared to up-and-down plowing.',
    takeaway: 'Contour plowing slows surface runoff velocities and traps eroding sediment on slopes.',
  },
  {
    id: 'land-q14',
    module: 'land',
    sectionId: 'ch-planning',
    topic: 'Sustainable Land-Use Planning (SLUP)',
    difficulty: 'Expert',
    prompt: 'In the Nilgiris Western Ghats case study, what key planning principle was recommended to curb catastrophic monsoonal landslides?',
    choices: [
      'Clearing all native shola trees to plant eucalyptus monocultures',
      'Slope-angle zoning, prohibition of unscientific hillside cutting, and restoration of native shola-grassland buffers',
      'Paving all agricultural hillsides with concrete slabs',
      'Channeling monsoon torrents through residential basements',
    ],
    answer: 1,
    explanation: 'Sustainable planning in fragile hill regions like the Nilgiris requires slope-angle zoning (restricting building on slopes >30°), regulating road excavation, mandating retaining walls, and preserving native deep-rooted shola vegetation that anchors colluvial soil.',
    takeaway: 'Land-use zoning must align with geophysical slope stability and watershed boundaries.',
  },
  {
    id: 'land-q15',
    module: 'land',
    sectionId: 'ch-summary',
    topic: 'Global Frameworks & SDG Target',
    difficulty: 'Standard',
    prompt: 'Target 15.3 of the United Nations Sustainable Development Goals commits global nations to achieve what specific outcome by 2030?',
    choices: [
      'Complete urbanization of 80% of all national parks',
      'Land Degradation Neutrality (LDN) and restoration of degraded soils',
      'Conversion of all natural wetlands into freshwater fish farms',
      'Diverting 70% of river flows into industrial canals',
    ],
    answer: 1,
    explanation: 'UN SDG Target 15.3 calls on all member nations to combat desertification, restore degraded land and soil (including areas affected by desertification, drought, and floods), and strive to achieve a Land Degradation Neutral (LDN) world by 2030.',
    takeaway: 'SDG 15.3 establishes Land Degradation Neutrality (LDN) as a cornerstone of planetary health.',
  },

  // ==========================================
  // MODULE 02: WATER (15 Syllabus-Aligned Questions)
  // ==========================================
  {
    id: 'water-q01',
    module: 'water',
    topic: 'Global Hydrological Distribution',
    difficulty: 'Standard',
    prompt: 'According to global water distribution records in the course notes, what percentage of Earth’s total water is freshwater, and where is the vast majority stored?',
    choices: [
      '10% freshwater, mostly found in tropical rivers',
      '2.5% freshwater, with nearly 79% locked in ice caps and glaciers',
      '5% freshwater, with 90% stored in subterranean aquifers',
      '0.5% freshwater, mostly circulating as atmospheric moisture',
    ],
    answer: 1,
    explanation: 'Only 2.5% of planetary water is freshwater (97.5% is saltwater in oceans). Of that 2.5%, approximately 79% is frozen in polar ice caps and glaciers, 20% is stored as groundwater, and only ~1% is readily accessible surface freshwater.',
    takeaway: 'A mere 2.5% of planetary water is freshwater, and nearly 79% of that is frozen in ice caps and glaciers.',
  },
  {
    id: 'water-q02',
    module: 'water',
    topic: 'Four Main Sources of Water',
    difficulty: 'Standard',
    prompt: 'Which of the following correctly identifies the four primary sources of water recognized in the syllabus?',
    choices: [
      'Rainwater, Surface water, Groundwater, and Water from Reclamation',
      'Ocean water, Cloud moisture, Glacial melt, and Deep mantle steam',
      'Atmospheric water, Swamp water, River water, and Thermal springs',
      'Bottled water, Municipal tap water, Dug well water, and Storm runoff',
    ],
    answer: 0,
    explanation: 'The course classifies water into four primary sources: (1) Rainwater (roofs and prepared catchments), (2) Surface water (rivers, lakes, reservoirs), (3) Groundwater (springs, wells, infiltration galleries, radial collector wells), and (4) Water from reclamation (desalination and treated wastewater reuse).',
    takeaway: 'The four recognized water sources are rainwater, surface water, groundwater, and reclaimed water.',
  },
  {
    id: 'water-q03',
    module: 'water',
    topic: 'Indian River Basins & Regional Asymmetry',
    difficulty: 'Advanced',
    prompt: 'Western Coast rivers in India drain only ~3% of the nation’s total land area, yet carry what proportion of India’s total water resources?',
    choices: [
      'About 1%',
      'About 11%',
      'About 35%',
      'Over 50%',
    ],
    answer: 1,
    explanation: 'Due to intense orographic rainfall along the Western Ghats, the short, steep west-flowing rivers of coastal Maharashtra, Karnataka, and Kerala drain only 3% of India’s land area but carry approximately 11% of the country’s total water resources.',
    takeaway: 'Western Coast rivers drain only 3% of land area but account for 11% of India’s water yield.',
  },
  {
    id: 'water-q04',
    module: 'water',
    topic: 'Sectoral Water Allocation',
    difficulty: 'Standard',
    prompt: 'What percentage of global water withdrawals is consumed by agriculture, and what is the recognized minimum basic household water requirement per person per day?',
    choices: [
      '35% agriculture; 15 litres/person/day',
      '69% agriculture; ~50 litres/person/day',
      '85% agriculture; 150 litres/person/day',
      '50% agriculture; 200 litres/person/day',
    ],
    answer: 1,
    explanation: 'Agriculture is the single largest consumer worldwide, accounting for 69% of withdrawals (compared to 15% industrial and 15% domestic). The recognized basic household water requirement for drinking, cooking, and sanitation is approximately 50 litres per person per day.',
    takeaway: 'Agriculture claims 69% of global freshwater use; basic human domestic survival requires 50 L/person/day.',
  },
  {
    id: 'water-q05',
    module: 'water',
    topic: 'India Water Deficit & Falkenmark Index',
    difficulty: 'Advanced',
    prompt: 'India holds ~1/6th of global population but only 1/25th of world water resources. With availability hovering near 1,600 m³/capita/year, which international category describes India’s condition?',
    choices: [
      'Water Abundance (above 2,500 m³/year)',
      'Adequate Water Supply (above 1,700 m³/year)',
      'Water Stressed Condition (1,000–1,700 m³/year)',
      'Absolute Water Scarcity (below 500 m³/year)',
    ],
    answer: 2,
    explanation: 'Under international Falkenmark criteria, renewable water availability between 1,000 and 1,700 m³/capita/year indicates a "Water Stressed" condition. India’s availability of ~1,600 m³/year places it under official water stress, rapidly heading toward scarcity (<1,000 m³/year).',
    takeaway: 'Per capita availability between 1,000 and 1,700 m³/year represents a Water Stressed condition.',
  },
  {
    id: 'water-q06',
    module: 'water',
    topic: 'Inter-Basin Water Transfer (IBWT)',
    difficulty: 'Standard',
    prompt: 'What is the primary engineering objective of Inter-Basin Water Transfer (IBWT) projects in India?',
    choices: [
      'To divert all freshwater rivers directly into coastal shipping canals',
      'To transfer water from surplus river basins to deficit river basins to balance distribution and mitigate flood/drought extremes',
      'To eliminate groundwater aquifers and switch entirely to ocean desalination',
      'To stop all river flows and convert natural floodplains into industrial zones',
    ],
    answer: 1,
    explanation: 'Inter-Basin Water Transfer conveys excess monsoon discharge from water-surplus basins to drought-prone, water-deficit basins, balancing regional disparities and mitigating recurring flood and drought cycles.',
    takeaway: 'IBWT balances hydrologic extremes by conveying water from surplus to deficit river basins.',
  },
  {
    id: 'water-q07',
    module: 'water',
    topic: 'National Water Development Agency (NWDA)',
    difficulty: 'Standard',
    prompt: 'In which year was the National Water Development Agency (NWDA) established by the Government of India to investigate river interlinking proposals?',
    choices: [
      '1947',
      '1965',
      '1980',
      '2005',
    ],
    answer: 2,
    explanation: 'The National Water Development Agency (NWDA) was constituted in July 1980 as an autonomous society under the Ministry of Water Resources to carry out comprehensive water balance studies and prepare feasibility reports for river interlinking.',
    takeaway: 'NWDA was established in 1980 to lead scientific investigations on interlinking river systems.',
  },
  {
    id: 'water-q08',
    module: 'water',
    topic: 'Himalayan Component of River Interlinking',
    difficulty: 'Advanced',
    prompt: 'How many inter-basin links are envisaged under the Himalayan Component of the river interlinking plan, and what are its targeted irrigation and power benefits?',
    choices: [
      '6 links providing 5 M Ha irrigation and 5,000 MW power',
      '14 links providing ~22 M Ha additional irrigation and 30,000 MW hydropower',
      '25 links providing 50 M Ha irrigation and 100,000 MW power',
      '8 links providing 10 M Ha irrigation with zero hydropower generation',
    ],
    answer: 1,
    explanation: 'The Himalayan Component includes 14 river links connecting the Brahmaputra, Ganga, and Eastern tributaries, targeted to provide ~22 million hectares of additional irrigation and approximately 30,000 MW of clean hydropower.',
    takeaway: 'The Himalayan Component includes 14 river links delivering 22 M Ha irrigation and 30,000 MW hydropower.',
  },
  {
    id: 'water-q09',
    module: 'water',
    topic: 'Peninsular Component of River Interlinking',
    difficulty: 'Advanced',
    prompt: 'Which of the following is one of the 16 major river links included in the Peninsular Component of India’s river interlinking program?',
    choices: [
      'Indus–Ganga Link',
      'Ken–Betwa Link',
      'Brahmaputra–Irrawaddy Link',
      'Sutlej–Hwang Ho Link',
    ],
    answer: 1,
    explanation: 'The Peninsular Component comprises 16 inter-basin links, prominently including the Ken–Betwa link, Godavari–Krishna links, Krishna–Pennar links, and Cauvery–Vaigai–Gundar link, utilizing ~69.6 TMCum of water to irrigate 13 M Ha.',
    takeaway: 'Ken–Betwa is a flagship link under the 16-link Peninsular river interlinking program.',
  },
  {
    id: 'water-q10',
    module: 'water',
    topic: 'Peninsular Hard-Rock Hydrogeology',
    difficulty: 'Expert',
    prompt: 'Hard-rock aquifers cover ~65% of India’s land area (Deccan basalts, crystalline granites). What are their typical well yields and storage characteristics?',
    choices: [
      'High sustained storage with well yields exceeding 100 lps',
      'Low-storage fracture aquifers where yields range between 2–10 lps and water tables drop sharply after 2–6 m of decline',
      'Unlimited artesian flows that never require mechanical pumping',
      'Completely impermeable formations with zero groundwater potential everywhere',
    ],
    answer: 1,
    explanation: 'Peninsular hard rocks constitute a low-storage, heterogeneous aquifer system where groundwater is restricted to weathered regolith and fractured zones down to 30–50 m depth. Well yields are modest (2–10 lps), and the water level drops sharply once the water table falls by 2–6 m.',
    takeaway: 'Peninsular hard-rock aquifers have limited storage, yielding 2–10 lps predominantly from shallow fractures.',
  },
  {
    id: 'water-q11',
    module: 'water',
    topic: 'Indo-Gangetic Alluvial Aquifers',
    difficulty: 'Advanced',
    prompt: 'What geological characteristic makes the Indo-Gangetic Plains India’s most prolific and productive groundwater reservoir?',
    choices: [
      'Deep solid crystalline granite bedrock without any fractures',
      'Thick multi-aquifer alluvial sand and gravel sediments exceeding 1,000 m depth with well yields of 25–50 lps',
      'An unbroken layer of impermeable volcanic basalt',
      'High geothermal pressure turning deep groundwater into boiling steam',
    ],
    answer: 1,
    explanation: 'The Indo-Gangetic alluvial basin covers ~850,000 km² and features thick Quaternary and Tertiary alluvial sand, silt, and gravel deposits exceeding 1,000 m thickness at places, supporting high-yield tubewells (25–50 lps).',
    takeaway: 'Indo-Gangetic alluvial deposits exceed 1,000 m in thickness, forming high-yield multi-aquifer systems (25–50 lps).',
  },
  {
    id: 'water-q12',
    module: 'water',
    topic: 'Conjunctive Water Use',
    difficulty: 'Standard',
    prompt: 'What is the precise definition of "Conjunctive Water Use" in irrigation engineering?',
    choices: [
      'Using water only once before discharging it into the sea',
      'The simultaneous, coordinated use of surface water and groundwater to meet crop demand and optimize storage',
      'Mixing industrial chemical effluent directly into municipal drinking water networks',
      'Extracting deep groundwater while leaving surface canal networks completely dry',
    ],
    answer: 1,
    explanation: 'Conjunctive water use refers to the combined, harmonious management of surface water (canals, reservoirs) and groundwater (tubewells) to meet crop evapotranspiration, buffer against droughts, and prevent waterlogging or salinization.',
    takeaway: 'Conjunctive use harmonizes surface and groundwater extraction to optimize agricultural water security.',
  },
  {
    id: 'water-q13',
    module: 'water',
    topic: 'Groundwater Contaminants',
    difficulty: 'Advanced',
    prompt: 'Which of the following is classified as a naturally occurring "geogenic" groundwater contaminant in Indian aquifers?',
    choices: [
      'Synthetic organophosphate pesticides',
      'Arsenic and Fluoride leached from native mineral rocks',
      'Coliform bacteria from open septic tanks',
      'Microplastics from synthetic textile effluents',
    ],
    answer: 1,
    explanation: 'Geogenic contaminants originate from natural rock weathering and mineral dissolution. In India, arsenic (particularly in the Bengal basin) and fluoride (in arid granite belts) are widespread geogenic toxins, affecting millions across 60% of districts.',
    takeaway: 'Arsenic and fluoride are geogenic contaminants derived from natural rock weathering.',
  },
  {
    id: 'water-q14',
    module: 'water',
    topic: 'Artificial Recharge Methods',
    difficulty: 'Standard',
    prompt: 'Which artificial recharge technique involves placing wells near a perennial river to draw surface water through the riverbed alluvium into the aquifer?',
    choices: [
      'Induced Recharge',
      'Deep Shaft High-Pressure Injection',
      'Overhead Cloud Seeding',
      'Ditch and Furrow Direct Spreading',
    ],
    answer: 0,
    explanation: 'Induced recharge is an indirect artificial recharge method where extraction wells are positioned adjacent to a river or lake. Pumping lowers the local groundwater table below river stage, inducing surface water to percolate through natural gravel filtration beds into the aquifer.',
    takeaway: 'Induced recharge draws river water into adjacent aquifers through alluvial bed filtration.',
  },
  {
    id: 'water-q15',
    module: 'water',
    topic: 'Seawater Ingress Control',
    difficulty: 'Expert',
    prompt: 'Which coastal groundwater management intervention is specifically recommended in the syllabus to control seawater intrusion into coastal aquifers?',
    choices: [
      'Pumping coastal wells at maximum capacity 24 hours a day',
      'Drilling ultra-deep borewells directly along the surf line',
      'Maintaining a minimum well setback distance of 50 m from the coast and creating an artificial freshwater recharge ridge',
      'Replacing all sandy beach dunes with impermeable concrete paving',
    ],
    answer: 2,
    explanation: 'To prevent seawater intrusion caused by a reversed hydraulic gradient, management guidelines mandate locating production wells at least 50 m inland, avoiding deep coastal pumping, reducing pump draw, and injecting treated freshwater to build a hydraulic barrier (freshwater ridge).',
    takeaway: 'A 50 m setback, shallow pump depths, and artificial freshwater ridges prevent coastal seawater intrusion.',
  },

  // ==========================================
  // MODULE 03: AIR (15 Syllabus-Aligned Questions)
  // ==========================================
  {
    id: 'air-q01',
    module: 'air',
    topic: 'Atmospheric Layers & Composition',
    difficulty: 'Standard',
    prompt: 'Which three gases account for over 99.9% of dry air in the troposphere (the lowest atmospheric layer up to ~12 km altitude)?',
    choices: [
      'Nitrogen (78.08%), Oxygen (20.95%), and Argon (0.93%)',
      'Oxygen, Carbon Dioxide, and Methane',
      'Nitrogen, Ozone, and Helium',
      'Argon, Neon, and Water Vapour',
    ],
    answer: 0,
    explanation: 'Nitrogen (~78.084%), Oxygen (~20.946%), and Argon (~0.934%) account for more than 99.9% of dry atmospheric air in the troposphere, which holds 80% of total atmospheric mass.',
    takeaway: 'Nitrogen, oxygen, and argon form 99.9% of dry atmospheric gases in the troposphere.',
  },
  {
    id: 'air-q02',
    module: 'air',
    topic: 'Primary vs Secondary Pollutants',
    difficulty: 'Standard',
    prompt: 'What fundamentally distinguishes a secondary air pollutant from a primary air pollutant?',
    choices: [
      'Secondary pollutants exist exclusively in solid crystalline form',
      'Secondary pollutants form in the atmosphere through chemical or photochemical reactions between precursor emissions',
      'Secondary pollutants originate solely from volcanic eruptions',
      'Secondary pollutants are emitted only by diesel automobile exhaust pipes',
    ],
    answer: 1,
    explanation: 'Primary pollutants (CO, SO₂, NO, particulate matter) are emitted directly from sources. Secondary pollutants (such as tropospheric ozone O₃, peroxyacetyl nitrate PAN, and acid rain) form when primary precursors undergo chemical reactions under sunlight.',
    takeaway: 'Secondary pollutants are synthesized in the atmosphere via chemical and photochemical reactions.',
  },
  {
    id: 'air-q03',
    module: 'air',
    topic: 'Forms of Air Pollutants',
    difficulty: 'Standard',
    prompt: 'According to environmental air quality classification, in what three physical states do air pollutants exist?',
    choices: [
      'Solid chunks, boiling magma, and lightning plasma',
      'Gases, finely divided solid aerosols, and finely divided liquid aerosols',
      'Pure vacuum, atomic ions, and subatomic neutrons',
      'Heavy rocks, dissolved ocean salts, and plant roots',
    ],
    answer: 1,
    explanation: 'Air pollutants disperse as: (1) Gases (CO, SO₂, NO₂), (2) Solid aerosols (dust, soot, smoke, fly ash), and (3) Liquid aerosols (acid mists, chemical droplets, sprays).',
    takeaway: 'Air pollutants occur in three physical forms: gases, solid aerosols, and liquid aerosols.',
  },
  {
    id: 'air-q04',
    module: 'air',
    topic: 'NAAQS Regulatory Framework',
    difficulty: 'Advanced',
    prompt: 'Under which statutory legislation are the National Ambient Air Quality Standards (NAAQS) notified by the Central Pollution Control Board (CPCB) in India?',
    choices: [
      'The Motor Vehicles Act, 1988',
      'The Air (Prevention and Control of Pollution) Act, 1981',
      'The Indian Forest Act, 1927',
      'The Public Liability Insurance Act, 1991',
    ],
    answer: 1,
    explanation: 'NAAQS are statutory ambient standards formulated by CPCB under Section 16(2)(h) of the Air (Prevention and Control of Pollution) Act, 1981. The standards cover 12 priority pollutants, updated comprehensively in November 2009.',
    takeaway: 'NAAQS are legally mandated under the Air (Prevention and Control of Pollution) Act, 1981.',
  },
  {
    id: 'air-q05',
    module: 'air',
    topic: 'National Air Quality Index (AQI)',
    difficulty: 'Standard',
    prompt: 'Launched in April 2015, how many criteria pollutants and colour-coded health categories comprise the Indian National AQI?',
    choices: [
      '3 pollutants and 2 categories (Safe, Unsafe)',
      '8 pollutants and 6 categories (Good to Severe: 401–500)',
      '15 pollutants and 10 categories',
      '5 pollutants and 4 categories',
    ],
    answer: 1,
    explanation: 'The Indian National AQI monitors 8 pollutants (PM10, PM2.5, NO₂, SO₂, CO, O₃, NH₃, Pb) mapped into 6 colour-coded categories: Good (0–50), Satisfactory (51–100), Moderate (101–200), Poor (201–300), Very Poor (301–400), and Severe (401–500).',
    takeaway: 'India’s AQI tracks 8 key pollutants across 6 categories, with 401–500 classified as Severe.',
  },
  {
    id: 'air-q06',
    module: 'air',
    topic: 'Health Effects: Carbon Monoxide (CO)',
    difficulty: 'Standard',
    prompt: 'Why is Carbon Monoxide (CO) inhalation exceptionally dangerous to human health even in small concentrations?',
    choices: [
      'It instantly freezes the vocal cords on contact',
      'It binds to blood hemoglobin ~200 times more strongly than oxygen, forming carboxyhemoglobin and causing cellular hypoxia',
      'It destroys tooth enamel through rapid calcification',
      'It causes immediate crystallization of stomach bile',
    ],
    answer: 1,
    explanation: 'Carbon monoxide binds to hemoglobin with an affinity approximately 200–250 times greater than oxygen, forming stable carboxyhemoglobin (COHb). This starves vital organs and brain tissues of oxygen, leading to dizziness, unconsciousness, and asphyxiation.',
    takeaway: 'CO binds to hemoglobin with >200x affinity compared to O₂, causing lethal carboxyhemoglobin hypoxia.',
  },
  {
    id: 'air-q07',
    module: 'air',
    topic: 'Fine Particulate Matter (PM2.5)',
    difficulty: 'Advanced',
    prompt: 'Why is fine particulate matter (PM2.5) considered far more hazardous to human health than coarse particles (PM10)?',
    choices: [
      'PM2.5 particles are radioactive heavy metals that glow in darkness',
      'PM2.5 particles bypass nasal hairs and ciliated mucus, penetrating deep into terminal lung alveoli and entering the systemic bloodstream',
      'PM2.5 particles only affect external skin pigment without entering lungs',
      'PM2.5 particles evaporate into harmless nitrogen gas upon breathing',
    ],
    answer: 1,
    explanation: 'Particles smaller than 2.5 micrometers (PM2.5) evade upper respiratory filtering mechanisms, penetrating directly into pulmonary alveoli where gas exchange occurs. They trigger chronic bronchitis, lung cancer, and diffuse into blood vessels causing cardiovascular infarction.',
    takeaway: 'PM2.5 penetrates deep alveolar tissue and enters the bloodstream, causing severe cardiopulmonary damage.',
  },
  {
    id: 'air-q08',
    module: 'air',
    topic: 'Industrial Particulate Control: ESP',
    difficulty: 'Advanced',
    prompt: 'Which industrial air pollution control device uses high-voltage corona discharge electrodes to ionize suspended particulates and collect them on grounded metal plates with >99% efficiency?',
    choices: [
      'Electrostatic Precipitator (ESP)',
      'Gravity Settling Chamber',
      'Venturi Scrubber',
      'Thermal Afterburner',
    ],
    answer: 0,
    explanation: 'An Electrostatic Precipitator (ESP) establishes an intense electrostatic field (40–70 kV) that ionizes flue gases. Suspended dust particles acquire negative charges and migrate toward positively grounded collection plates, achieving >99% collection efficiency for fly ash.',
    takeaway: 'Electrostatic Precipitators (ESPs) use high-voltage electrical fields to capture particulates at >99% efficiency.',
  },
  {
    id: 'air-q09',
    module: 'air',
    topic: 'Particulate Control: Cyclone Separator',
    difficulty: 'Standard',
    prompt: 'How does a cyclone separator remove coarse particulate matter (>10 µm) from an industrial gas stream?',
    choices: [
      'By cooling gas until particulates freeze and crack',
      'By spinning incoming gas in a vortex where centrifugal force hurls heavier particles against chamber walls to settle into a hopper',
      'By passing gas through magnetic copper coils',
      'By dissolving the particles in concentrated sulfuric acid',
    ],
    answer: 1,
    explanation: 'Cyclone separators use centrifugal inertia. The gas stream enters tangentially, forming a downward spiral vortex. Centrifugal force flings heavier particles (>10 µm) against the conical outer wall where friction slows them, dropping them into a collection dust hopper.',
    takeaway: 'Cyclone separators employ centrifugal vortex inertia to separate coarse particulate matter.',
  },
  {
    id: 'air-q10',
    module: 'air',
    topic: 'Gaseous Emission Control: Wet Scrubbers',
    difficulty: 'Advanced',
    prompt: 'In flue-gas desulfurization (FGD), how do wet scrubbers effectively eliminate sulfur dioxide (SO₂) emissions from coal-fired power plants?',
    choices: [
      'By passing the gas through high-intensity sound waves',
      'By spraying an alkaline slurry (such as limestone or lime) that chemically neutralizes acidic SO₂ into calcium sulfite and gypsum',
      'By passing flue gas through activated charcoal refrigeration coils',
      'By burning the SO₂ gas at 3,000°C to destroy all sulfur atoms',
    ],
    answer: 1,
    explanation: 'Wet scrubbers spray an alkaline washing reagent (limestone CaCO₃ or lime Ca(OH)₂ slurry) through the ascending flue gas stream. Acidic SO₂ reacts chemically with the alkaline liquid, neutralizing into calcium sulfite and calcium sulfate (gypsum), removing >90% of SO₂.',
    takeaway: 'Wet scrubbers neutralize acidic SO₂ flue gas by spraying alkaline limestone/lime slurry.',
  },
  {
    id: 'air-q11',
    module: 'air',
    topic: 'Stratospheric Ozone & Dobson Units',
    difficulty: 'Standard',
    prompt: 'At what atmospheric altitude is stratospheric ozone concentrated, and what is the standard baseline thickness of the healthy ozone layer measured in Dobson Units (DU)?',
    choices: [
      'At 2–5 km altitude; baseline of 50 DU',
      'At 20–30 km altitude; normal baseline of ~300 DU (with an ozone hole defined below 200 DU)',
      'At 80–100 km altitude; baseline of 1,000 DU',
      'At sea level; baseline of 10 DU',
    ],
    answer: 1,
    explanation: 'The protective ozone layer resides in the stratosphere at ~20–30 km altitude (peaking near 24 km). Its column thickness is measured in Dobson Units (1 DU = 0.01 mm pure O₃ at STP). Healthy baseline levels are ~300 DU; an "ozone hole" is formally defined when column thickness drops below 200 DU.',
    takeaway: 'The stratospheric ozone layer resides at 20–30 km altitude with a ~300 DU healthy baseline.',
  },
  {
    id: 'air-q12',
    module: 'air',
    topic: 'Catalytic Ozone Destruction Cycle',
    difficulty: 'Expert',
    prompt: 'In the stratosphere, how does a single chlorine atom released from photolyzed CFCs trigger catalytic destruction of ozone molecules?',
    choices: [
      'It freezes ozone molecules into solid ice crystals',
      'It participates in a cyclic catalytic reaction (Cl + O₃ → ClO + O₂ followed by ClO + O → Cl + O₂), destroying up to 100,000 O₃ molecules',
      'It transforms oxygen atoms into lead atoms through nuclear fusion',
      'It absorbs all solar heat so that ozone cannot reproduce',
    ],
    answer: 1,
    explanation: 'Solar UV radiation cleaves chlorine atoms from CFCs. The free chlorine radical acts as a catalytic agent: Cl + O₃ → ClO + O₂, and then ClO + O → Cl + O₂. The regenerated chlorine atom attacks another ozone molecule, destroying up to 100,000 ozone molecules before being deactivated.',
    takeaway: 'A single chlorine radical catalytically destroys up to 100,000 stratospheric ozone molecules.',
  },
  {
    id: 'air-q13',
    module: 'air',
    topic: 'The Montreal Protocol',
    difficulty: 'Standard',
    prompt: 'What international multilateral treaty signed in 1987 successfully mandated the global phase-out of ozone-depleting chlorofluorocarbons (CFCs)?',
    choices: [
      'The Kyoto Protocol',
      'The Montreal Protocol',
      'The Paris Agreement',
      'The Ramsar Convention',
    ],
    answer: 1,
    explanation: 'The Montreal Protocol on Substances that Deplete the Ozone Layer was adopted in 1987 and ratified by 198 countries. It systematically phased out the production of CFCs, halons, and carbon tetrachloride, allowing the ozone layer to recover toward pre-1980 levels by ~2050–2060.',
    takeaway: 'The 1987 Montreal Protocol successfully phased out CFCs, enabling stratospheric ozone recovery.',
  },
  {
    id: 'air-q14',
    module: 'air',
    topic: 'Photochemical Smog & PAN',
    difficulty: 'Advanced',
    prompt: 'What environmental conditions and precursor chemicals trigger the formation of toxic photochemical smog in urban atmospheres?',
    choices: [
      'High humidity, freezing temperatures, and sulfur dioxide emissions at midnight',
      'Intense solar UV radiation reacting with nitrogen oxides (NOₓ) and volatile organic compounds (VOCs), generating ground-level ozone and Peroxyacetyl Nitrate (PAN)',
      'Heavy ocean rains washing pure methane through city sewer pipes',
      'Volcanic dust clouds interacting with agricultural fertilizer dust in total darkness',
    ],
    answer: 1,
    explanation: 'Photochemical smog occurs in sunny, warm urban air when sunlight photolyzes nitrogen dioxide (NO₂ → NO + O), freeing atomic oxygen to produce ground-level ozone (O₃). Ozone reacts with volatile hydrocarbons to form Peroxyacetyl Nitrate (PAN), a potent eye irritant and phytotoxin.',
    takeaway: 'Photochemical smog requires sunlight, NOₓ, and VOCs to form ground-level ozone and toxic PAN.',
  },
  {
    id: 'air-q15',
    module: 'air',
    topic: 'Acid Rain & Material Degradation',
    difficulty: 'Advanced',
    prompt: 'How does atmospheric acid deposition (acid rain containing H₂SO₄ and HNO₃) cause severe deterioration of historic marble monuments like the Taj Mahal?',
    choices: [
      'It coats the marble in an impenetrable diamond crust',
      'It reacts chemically with calcium carbonate (CaCO₃) in marble to form soluble calcium sulfate (gypsum), causing flaking and "marble cancer"',
      'It turns marble into pure combustible coal',
      'It causes marble stones to spontaneously ignite upon drying',
    ],
    answer: 1,
    explanation: 'Sulfur dioxide emissions react with atmospheric moisture to form sulfuric acid (H₂SO₄). When deposited on marble structures (CaCO₃), it reacts to form gypsum (CaSO₄·2H₂O), which is water-soluble and expands, leading to surface pitting, discolouration, and crumbling ("marble cancer").',
    takeaway: 'Acid rain converts marble calcium carbonate into soluble gypsum, producing destructive marble cancer.',
  },

  // ==========================================
  // MODULE 04: BIODIVERSITY (15 Syllabus-Aligned Questions)
  // ==========================================
  {
    id: 'bio-q01',
    module: 'biodiversity',
    topic: 'Levels of Biodiversity',
    difficulty: 'Standard',
    prompt: 'What are the three canonical, hierarchical tiers of biodiversity recognized in conservation science?',
    choices: [
      'Genetic diversity, Species diversity, and Ecosystem diversity',
      'Plant diversity, Animal diversity, and Microscopic diversity',
      'Forest diversity, Marine diversity, and Desert diversity',
      'Local diversity, Continental diversity, and Cosmic diversity',
    ],
    answer: 0,
    explanation: 'Biodiversity operates across three fundamental organizational levels: (1) Genetic diversity (variations in genetic alleles within a species), (2) Species diversity (richness and relative abundance of species within a habitat), and (3) Ecosystem diversity (variety of habitats, biotic communities, and ecological processes).',
    takeaway: 'Genetic, species, and ecosystem diversity constitute the three canonical tiers of biodiversity.',
  },
  {
    id: 'bio-q02',
    module: 'biodiversity',
    topic: 'Genetic Diversity & Resilience',
    difficulty: 'Standard',
    prompt: 'Why is high genetic diversity within a biological population essential for long-term species survival?',
    choices: [
      'It ensures all organisms look completely identical',
      'It provides a broad gene pool allowing populations to adapt to novel pathogens, environmental changes, and selective pressures',
      'It completely halts all future evolutionary change',
      'It prevents seeds from ever germinating in soil',
    ],
    answer: 1,
    explanation: 'High genetic diversity maintains a diverse gene pool. When novel diseases, climate fluctuations, or environmental stressors arise, individuals carrying resistant genetic alleles survive to reproduce, preventing catastrophic population collapses and extinctions.',
    takeaway: 'Genetic diversity equips populations with the adaptive resilience needed to survive environmental shifts.',
  },
  {
    id: 'bio-q03',
    module: 'biodiversity',
    topic: 'Global Species Count & Hotspots',
    difficulty: 'Advanced',
    prompt: 'Approximately how many biological species have been scientifically identified to date, and how many recognized global biodiversity hotspots are represented in India?',
    choices: [
      '100,000 species identified; 1 hotspot in India',
      '~1.8 million species identified; 4 global hotspots represented in India (Western Ghats, Eastern Himalayas, Indo-Burma, Sundaland)',
      '50 million species identified; 20 hotspots in India',
      '10,000 species identified; zero hotspots in India',
    ],
    answer: 1,
    explanation: 'Taxonomists have documented approximately 1.8 million species out of an estimated 5–30 million global total. India is recognized as a mega-diversity nation harboring 4 of the world’s 36 biodiversity hotspots: Western Ghats, Eastern Himalayas, Indo-Burma, and Sundaland (Nicobar Islands).',
    takeaway: '~1.8 million species have been catalogued, and India hosts 4 critical global biodiversity hotspots.',
  },
  {
    id: 'bio-q04',
    module: 'biodiversity',
    topic: 'Categories of Biodiversity Value',
    difficulty: 'Standard',
    prompt: 'Which biodiversity valuation category refers to preserving biological species for their potential, currently unforeseen future benefits in medicine or biotechnology?',
    choices: [
      'Consumptive use value',
      'Productive commercial value',
      'Option value',
      'Social prestige value',
    ],
    answer: 2,
    explanation: 'Option value represents the potential future economic, agricultural, or medicinal utility of biological species that are not yet discovered or commercially exploited today (e.g., wild plants containing cures for emerging diseases).',
    takeaway: 'Option value reflects the future potential utility of preserved biological resources.',
  },
  {
    id: 'bio-q05',
    module: 'biodiversity',
    topic: 'Medicinal Plants & Pharmacology',
    difficulty: 'Standard',
    prompt: 'According to the curriculum notes, what percentage of the world’s population relies on traditional plant-derived medicines, and which life-saving antimalarial drug was extracted from Cinchona bark?',
    choices: [
      '10% of population; Penicillin',
      'Over 70% of population; Quinine',
      '25% of population; Aspirin',
      '95% of population; Morphine only',
    ],
    answer: 1,
    explanation: 'Over 70% of the global population depends on traditional herbal medicines for primary health care. Famous pharmaceutical compounds derived from wild biodiversity include Quinine (antimalarial from Cinchona tree bark), Morphine (analgesic from opium poppy), and Penicillin (antibiotic from Penicillium fungi).',
    takeaway: 'Over 70% of humans depend on plant medicines; Quinine originates from wild Cinchona bark.',
  },
  {
    id: 'bio-q06',
    module: 'biodiversity',
    topic: 'In-Situ vs Ex-Situ Conservation',
    difficulty: 'Standard',
    prompt: 'What is the fundamental scientific difference between in-situ and ex-situ biodiversity conservation?',
    choices: [
      'In-situ protects species inside their natural wild ecosystems, whereas ex-situ preserves components outside natural habitats in artificial facilities',
      'In-situ applies only to marine fish; ex-situ applies only to forest trees',
      'In-situ involves hunting animals; ex-situ involves breeding animals in factories',
      'There is no distinction; both terms refer strictly to urban botanical gardens',
    ],
    answer: 0,
    explanation: 'In-situ conservation protects wild species within their native ecosystems (National Parks, Sanctuaries, Biosphere Reserves). Ex-situ conservation safeguards genetic material outside their natural habitat in controlled environments (seed vaults, gene banks, zoological gardens, botanical arboretums).',
    takeaway: 'In-situ preserves species in native ecosystems; ex-situ protects genetic stock off-site in facilities.',
  },
  {
    id: 'bio-q07',
    module: 'biodiversity',
    topic: 'Protected Areas: Parks vs Sanctuaries',
    difficulty: 'Advanced',
    prompt: 'How do statutory rules governing National Parks differ from Wildlife Sanctuaries under the Wildlife (Protection) Act, 1972?',
    choices: [
      'National Parks permit commercial timber logging, whereas Sanctuaries do not',
      'National Parks enjoy total protection with absolute prohibition on livestock grazing and private ownership rights; Sanctuaries permit limited regulated human activities',
      'Sanctuaries have higher legal status than National Parks',
      'National Parks are owned by private corporations, while Sanctuaries are owned by the UN',
    ],
    answer: 1,
    explanation: 'National Parks have higher statutory protection: no human settlement, private land rights, or livestock grazing are permitted. In Wildlife Sanctuaries, certain traditional rights like limited cattle grazing, transit, and collection of minor forest produce may be permitted by the Chief Wildlife Warden.',
    takeaway: 'National Parks prohibit all private rights and grazing; Wildlife Sanctuaries allow limited regulated use.',
  },
  {
    id: 'bio-q08',
    module: 'biodiversity',
    topic: 'Gene Banks & Cryopreservation',
    difficulty: 'Advanced',
    prompt: 'In ex-situ gene banks, what physical preservation technique stores crop germplasm, pollen, and animal embryos indefinitely at −196°C in liquid nitrogen?',
    choices: [
      'Thermal Pyrolysis',
      'Cryopreservation',
      'Steam Autoclaving',
      'Solar Dehydration',
    ],
    answer: 1,
    explanation: 'Cryopreservation preserves seeds, pollen, tissue cultures, and embryos at ultra-low cryogenic temperatures (−196°C using liquid nitrogen). At this temperature, cellular metabolic and enzymatic activities cease, maintaining genetic integrity for decades or centuries.',
    takeaway: 'Cryopreservation uses liquid nitrogen at −196°C to arrest cellular metabolism and store germplasm.',
  },
  {
    id: 'bio-q09',
    module: 'biodiversity',
    topic: 'Threats to Biodiversity (HIPPO)',
    difficulty: 'Standard',
    prompt: 'Globally, which factor is recognized by conservation biologists as the single greatest driver of species endangerment and mass extinction?',
    choices: [
      'Habitat loss, fragmentation, and degradation',
      'Cosmic asteroid impacts',
      'Volcanic ash clouds in polar regions',
      'Natural aging of animal populations',
    ],
    answer: 0,
    explanation: 'Habitat destruction, degradation, and fragmentation (caused by agricultural conversion, deforestation, damming, and urbanization) is the leading driver of species extinction worldwide, outranking invasive alien species, pollution, and overexploitation.',
    takeaway: 'Habitat destruction and fragmentation represent the single greatest threat to planetary biodiversity.',
  },
  {
    id: 'bio-q10',
    module: 'biodiversity',
    topic: 'Freshwater Ecosystems: Lentic vs Lotic',
    difficulty: 'Standard',
    prompt: 'In aquatic ecology, what is the fundamental difference between lentic and lotic freshwater habitats?',
    choices: [
      'Lentic waters are standing or stagnant (lakes, ponds, swamps); lotic waters are running or flowing (rivers, streams, brooks)',
      'Lentic waters contain 100% saltwater; lotic waters contain 100% distilled rainwater',
      'Lentic systems exist only beneath glaciers; lotic systems exist only in deserts',
      'Lentic systems contain no plant life; lotic systems contain no animal life',
    ],
    answer: 0,
    explanation: 'Freshwater ecosystems are divided into lentic (calm, standing water bodies like lakes, ponds, bogs, and reservoirs) and lotic (moving, directional flowing water systems like rivers, creeks, and mountain streams).',
    takeaway: 'Lentic refers to standing water bodies (lakes); lotic refers to flowing water channels (rivers).',
  },
  {
    id: 'bio-q11',
    module: 'biodiversity',
    topic: 'Lake Ecological Zonation',
    difficulty: 'Advanced',
    prompt: 'Which zone of a freshwater lake ecosystem is the shallow, well-lit perimeter where sunlight reaches the bottom, supporting rooted aquatic vegetation?',
    choices: [
      'Profundal zone',
      'Littoral zone',
      'Limnetic zone',
      'Abyssal benthic trench',
    ],
    answer: 1,
    explanation: 'The littoral zone is the shallow near-shore margin of a lake where sunlight penetrates fully to the sediment bed, allowing emergent, floating, and submerged macrophytes (reeds, water lilies) to thrive alongside rich invertebrate communities.',
    takeaway: 'The littoral zone is the shallow, sunlit near-shore lake region supporting rooted macrophytes.',
  },
  {
    id: 'bio-q12',
    module: 'biodiversity',
    topic: 'Estuarine Ecosystems & Mangroves',
    difficulty: 'Advanced',
    prompt: 'What unique morphological adaptation allows mangrove trees to survive in oxygen-depleted, waterlogged saline soils of estuarine ecosystems?',
    choices: [
      'Thick woolly needles to retain winter snow',
      'Specialized aerial breathing roots called pneumatophores with lenticels for atmospheric gas exchange',
      'Deep taproots that reach Earth’s molten mantle',
      'Carnivorous leaves that consume flying insects for nitrogen',
    ],
    answer: 1,
    explanation: 'Mangroves growing in anoxic, tidal mudflats possess specialized vertical aerial roots called pneumatophores (breathing roots) covered with porous lenticels that take in oxygen directly from the air during low tide to aerate submerged root tissues.',
    takeaway: 'Pneumatophores are specialized aerial roots enabling mangroves to respire in waterlogged anoxic mud.',
  },
  {
    id: 'bio-q13',
    module: 'biodiversity',
    topic: 'Forest Biome Services',
    difficulty: 'Standard',
    prompt: 'Forest ecosystems cover approximately 31% of Earth’s total land area. What vital ecological role do they play in global biogeochemical regulation?',
    choices: [
      'They produce 100% of all mineral iron ores found in Earth’s crust',
      'They serve as immense terrestrial carbon sinks, regulate microclimates, anchor soils against erosion, and host >80% of terrestrial biodiversity',
      'They accelerate global desertification by draining underground aquifers',
      'They prevent clouds from forming over continental interiors',
    ],
    answer: 1,
    explanation: 'Forests cover ~4.06 billion hectares (31% of land). They sequester billions of tons of carbon dioxide, transpire moisture to generate regional rainfall, mitigate flooding, stabilize topsoils, and provide habitat for over 80% of terrestrial plant and animal species.',
    takeaway: 'Forests cover 31% of land, serving as vital terrestrial carbon sinks and biodiversity reservoirs.',
  },
  {
    id: 'bio-q14',
    module: 'biodiversity',
    topic: 'Biogeochemical Nutrient Cycling',
    difficulty: 'Standard',
    prompt: 'What constitutes a "biogeochemical cycle" in ecosystem ecology?',
    choices: [
      'The seasonal migration of birds between polar circles',
      'The circular pathway through which chemical nutrients (Carbon, Nitrogen, Phosphorus, Water) cycle continuously between abiotic environmental reservoirs and living biotic communities',
      'The mechanical breakdown of rocks by earthquakes',
      'The rotation of tectonic plates around Earth’s core',
    ],
    answer: 1,
    explanation: 'Biogeochemical cycles represent the continuous circulation of essential bio-elements (C, N, P, S, H₂O) through abiotic geological reservoirs (atmosphere, lithosphere, hydrosphere) and living organisms (producers, consumers, decomposers) in an ecosystem.',
    takeaway: 'Biogeochemical cycles circulate vital chemical elements between living organisms and physical reservoirs.',
  },
  {
    id: 'bio-q15',
    module: 'biodiversity',
    topic: 'Biomagnification in Trophic Chains',
    difficulty: 'Expert',
    prompt: 'Why do non-biodegradable synthetic chemicals like DDT and heavy metals exhibit dangerous "biomagnification" across ecological food webs?',
    choices: [
      'They dissolve completely in rainwater and disappear from the food chain',
      'They are fat-soluble and resistant to metabolic breakdown, accumulating in higher concentrations at each successive trophic feeding tier',
      'They are consumed only by microscopic decomposers and never harm top carnivores',
      'They spontaneously transform into harmless sugars inside animal digestive systems',
    ],
    answer: 1,
    explanation: 'Biomagnification occurs with persistent, lipophilic (fat-soluble) pollutants like organochlorines (DDT) and methylmercury. Organisms cannot excrete them rapidly, so as biomass moves up trophic levels, top predators (raptors, apex carnivores, humans) accumulate lethal toxic concentrations.',
    takeaway: 'Biomagnification progressively concentrates non-biodegradable toxins at higher trophic levels.',
  },

  // ==========================================
  // MODULE 05: GLOBAL WARMING & EIA (15 Syllabus-Aligned Questions)
  // ==========================================
  {
    id: 'warm-q01',
    module: 'warming',
    topic: 'Planetary Energy Balance & Albedo',
    difficulty: 'Standard',
    prompt: 'According to planetary radiative equilibrium calculations, about how much incoming solar radiation is directly reflected back into space (global albedo)?',
    choices: ['10%', '30%', '50%', '70%'],
    answer: 1,
    explanation: 'Earth’s global planetary albedo is approximately 0.30 (30%), reflecting incoming solar irradiance back to space via clouds, atmospheric aerosols, and reflective surfaces (polar ice caps, snow fields, desert sands), while absorbing the remaining 70%.',
    takeaway: 'Earth reflects roughly 30% of incoming solar energy (albedo) and absorbs the remaining 70%.',
  },
  {
    id: 'warm-q02',
    module: 'warming',
    topic: 'The Natural Greenhouse Effect',
    difficulty: 'Standard',
    prompt: 'What are the estimated global mean surface temperatures of Earth WITHOUT and WITH the natural greenhouse effect?',
    choices: [
      '−18°C without, and +15°C with',
      '+15°C without, and +30°C with',
      '0°C without, and +18°C with',
      '−30°C without, and +18°C with',
    ],
    answer: 0,
    explanation: 'Without natural greenhouse gases (water vapor, CO₂, CH₄), Earth’s radiative equilibrium temperature would be approximately −18°C (a frozen, lifeless world). Atmospheric infrared absorption creates a natural +33°C warming, sustaining an hospitable mean temperature of +15°C.',
    takeaway: 'The natural greenhouse effect warms Earth by +33°C, from −18°C to a hospitable +15°C.',
  },
  {
    id: 'warm-q03',
    module: 'warming',
    topic: 'Anthropogenic Greenhouse Gases',
    difficulty: 'Standard',
    prompt: 'Which human agricultural and industrial activities are the primary anthropogenic sources of Methane (CH₄) and Nitrous Oxide (N₂O)?',
    choices: [
      'Nuclear fission reactors and solar panel manufacturing',
      'Flooded paddy rice cultivation, ruminant livestock digestion, and agricultural nitrogen fertilizer application',
      'Deep coal mining and granite countertop quarrying',
      'Hydroelectric reservoir operation and desalination plants',
    ],
    answer: 1,
    explanation: 'Methane (CH₄) is generated anaerobically from flooded rice paddies, enteric fermentation in cattle, and municipal landfills. Nitrous oxide (N₂O) is primarily emitted from synthetic nitrogen fertilizer application in agricultural soils and chemical manufacturing.',
    takeaway: 'Enteric cattle fermentation and paddy rice yield CH₄; agricultural nitrogen fertilizers emit N₂O.',
  },
  {
    id: 'warm-q04',
    module: 'warming',
    topic: 'Indicators of Global Warming',
    difficulty: 'Advanced',
    prompt: 'Which of the following sets represents documented empirical indicators of anthropogenically enhanced global warming?',
    choices: [
      'Expanding continental ice sheets and declining global sea surface temperatures',
      'Rising air surface temperatures, rising sea levels, ocean heat content expansion, and shrinking Arctic sea ice and alpine glaciers',
      'Decreasing tropospheric humidity and falling ocean acidity',
      'Increase in global permafrost thickness and fewer intense heatwaves',
    ],
    answer: 1,
    explanation: 'The 10 canonical indicators of planetary warming include rising tropospheric air temperatures, rising sea surface temperatures, expanding ocean heat content, rising sea levels, and increased humidity, alongside shrinking alpine glaciers, snow cover, and Arctic sea ice extent.',
    takeaway: 'Rising temperatures, sea levels, and ocean heat accompany shrinking glaciers and Arctic sea ice.',
  },
  {
    id: 'warm-q05',
    module: 'warming',
    topic: 'Climate Change Health Impacts',
    difficulty: 'Advanced',
    prompt: 'According to World Health Organization (WHO) and IPCC findings cited in the notes, what are the primary pathways through which climate change threatens human health?',
    choices: [
      'Increased risk of frostbite in equatorial deserts',
      'Thermal heat stress, expansion of vector-borne disease habitats (malaria, dengue), worsening malnutrition, and clean water scarcity',
      'Sudden permanent blindness from atmospheric nitrogen',
      'Accelerated bone calcification due to ambient argon',
    ],
    answer: 1,
    explanation: 'WHO estimates climate change causes >150,000 deaths annually through lethal heatwaves, expanding geographic ranges of vector-borne mosquitoes (malaria, dengue), exacerbated malnutrition from crop failures, and contaminated waterborne diarrheal outbreaks.',
    takeaway: 'Heatwaves, expanding vector-borne diseases, and water scarcity cause >150,000 annual climate-related deaths.',
  },
  {
    id: 'warm-q06',
    module: 'warming',
    topic: 'Environmental Impact Assessment (EIA) Definition',
    difficulty: 'Standard',
    prompt: 'What is the precise formal definition and purpose of an Environmental Impact Assessment (EIA)?',
    choices: [
      'A post-construction audit designed to fine corporations after environmental disasters have occurred',
      'A proactive, anticipatory planning study that predicts, evaluates, and mitigates the environmental and socioeconomic consequences of a proposed project before approval',
      'A public relations advertisement promoting rapid industrialization without environmental constraints',
      'A geological exploration method used exclusively to locate underground petroleum reserves',
    ],
    answer: 1,
    explanation: 'EIA is an anticipatory environmental management tool designed to identify, predict, and evaluate the physical, ecological, and social impacts of proposed developmental activities before administrative decisions and project construction commence.',
    takeaway: 'EIA is a proactive planning study that identifies and mitigates environmental impacts prior to project approval.',
  },
  {
    id: 'warm-q07',
    module: 'warming',
    topic: 'Three Core Ethical Values of EIA',
    difficulty: 'Standard',
    prompt: 'Which three foundational core ethical values govern the international practice of Environmental Impact Assessment?',
    choices: [
      'Integrity, Utility, and Sustainability',
      'Speed, Profitability, and Deregulation',
      'Air Quality, Water Volume, and Land Acreage',
      'Exemption, Compliance, and Arbitration',
    ],
    answer: 0,
    explanation: 'The International Association for Impact Assessment (IAIA) defines the three foundational core values of EIA as: (1) Integrity (fair, rigorous, unbiased execution), (2) Utility (providing practical, balanced information for decision-makers), and (3) Sustainability (safeguarding ecological integrity for future generations).',
    takeaway: 'Integrity, utility, and sustainability are the three core ethical pillars of EIA.',
  },
  {
    id: 'warm-q08',
    module: 'warming',
    topic: 'Evolution & History of EIA Legislation',
    difficulty: 'Advanced',
    prompt: 'Where did Environmental Impact Assessment (EIA) formally originate, and under which landmark legislation was it first mandated into federal law?',
    choices: [
      'In India under the Wildlife Protection Act, 1972',
      'In the United States under the National Environmental Policy Act (NEPA) of 1969 (effective 1970)',
      'In the United Kingdom under the Clean Air Act, 1956',
      'In Switzerland at the 1992 Earth Summit',
    ],
    answer: 1,
    explanation: 'EIA was first mandated into federal law by the United States Congress through the National Environmental Policy Act (NEPA) of 1969 (which came into force on January 1, 1970). It was subsequently adopted by the World Bank in the 1980s and formalized in over 100 countries.',
    takeaway: 'EIA originated under the landmark US National Environmental Policy Act (NEPA) of 1969.',
  },
  {
    id: 'warm-q09',
    module: 'warming',
    topic: 'EIA Project Classification (Category A vs B)',
    difficulty: 'Advanced',
    prompt: 'Under Indian EIA Notifications, how are development projects categorized for regulatory clearance?',
    choices: [
      'Category A projects require Central clearance from MoEFCC with mandatory EIA; Category B projects are appraised at State level (SEIAA), subdivided into B1 (requiring EIA) and B2 (exempt)',
      'Category A projects are completely exempt; Category B projects require military clearance',
      'All projects are classified into a single uniform category regardless of scale or pollution potential',
      'Categories are determined solely by the number of parking spaces provided',
    ],
    answer: 0,
    explanation: 'Category A projects (large ports, nuclear plants, major highways) require prior environmental clearance from the central MoEFCC with mandatory EIA and public consultation. Category B projects are handled by State Environmental Impact Assessment Authorities (SEIAA), with B1 requiring EIA and B2 exempt.',
    takeaway: 'Category A requires Central MoEFCC clearance with EIA; Category B is appraised at State SEIAA level.',
  },
  {
    id: 'warm-q10',
    module: 'warming',
    topic: 'Sequential Phases: Screening & Scoping',
    difficulty: 'Standard',
    prompt: 'In the standard EIA sequence, what specific task is performed during the "Scoping" stage?',
    choices: [
      'Demolishing existing buildings to make space for the project',
      'Determining project boundaries, identifying key environmental issues, and establishing detailed Terms of Reference (ToR) for the EIA study',
      'Calculating corporate tax incentives for the developer',
      'Distributing monetary compensation to displaced families before any surveys',
    ],
    answer: 1,
    explanation: 'While "Screening" determines whether a project requires an EIA, "Scoping" defines the spatial and temporal boundaries of the assessment, identifies priority ecological and social concerns, and formulates the binding Terms of Reference (ToR) for baseline surveys.',
    takeaway: 'Scoping establishes the boundaries, critical impacts, and Terms of Reference (ToR) for an EIA study.',
  },
  {
    id: 'warm-q11',
    module: 'warming',
    topic: 'Baseline Environmental Data Collection',
    difficulty: 'Advanced',
    prompt: 'What are the standard regulatory guidelines for collecting baseline environmental data during an EIA study in India?',
    choices: [
      'Data can be fabricated using internet search engines without visiting the project site',
      'Field monitoring must cover one full representative season (usually pre-monsoon, winter, or post-monsoon, strictly excluding the monsoon season) across air, water, noise, soil, and ecology',
      'Monitoring is required for exactly 24 hours only',
      'Data is collected exclusively during the heaviest monsoon rainfall week',
    ],
    answer: 1,
    explanation: 'Baseline data collection requires rigorous on-site scientific monitoring across physical (air, surface/ground water, noise, soil), biological (flora, fauna, habitats), and socioeconomic components over one full representative season (excluding the monsoon, when precipitation artificially washes out pollutants).',
    takeaway: 'Baseline environmental monitoring covers one full representative season (excluding monsoon).',
  },
  {
    id: 'warm-q12',
    module: 'warming',
    topic: 'Public Consultation & Public Hearing Stage',
    difficulty: 'Standard',
    prompt: 'What is the mandatory function of the "Public Hearing" stage conducted by State Pollution Control Boards during an EIA?',
    choices: [
      'To sell corporate shares of the proposed project to local residents',
      'To transparently present project details and environmental findings to local affected communities, documenting their concerns and objections for incorporation into the final report',
      'To celebrate the project launch with local political leaders',
      'To arrest citizens who oppose the industrial development',
    ],
    answer: 1,
    explanation: 'Public Consultation ensures participatory democracy. The State Pollution Control Board conducts a formal public hearing near the project site where local project-affected people review the summary EIA, voice ecological or livelihood concerns, and ensure their feedback is integrated into the final EMP.',
    takeaway: 'Public hearings provide a democratic forum for affected citizens to voice concerns before project approval.',
  },
  {
    id: 'warm-q13',
    module: 'warming',
    topic: 'Environmental Management Plan (EMP)',
    difficulty: 'Standard',
    prompt: 'Which critical planning document formulated in the EIA process details specific pollution mitigation technologies, budgetary allocations, and long-term compliance monitoring schedules?',
    choices: [
      'Initial Screening Application',
      'Environmental Management Plan (EMP)',
      'Corporate Balance Sheet',
      'Land Title Registration Deed',
    ],
    answer: 1,
    explanation: 'The Environmental Management Plan (EMP) is the operational backbone of an EIA. It specifies tangible mitigation measures (effluent treatment, green belts, acoustic barriers), institutional responsibilities, capital/recurring budget allocations, and post-clearance monitoring schedules.',
    takeaway: 'The Environmental Management Plan (EMP) outlines actionable mitigation measures, budgets, and monitoring.',
  },
  {
    id: 'warm-q14',
    module: 'warming',
    topic: 'Key Benefits of EIA in Development Planning',
    difficulty: 'Standard',
    prompt: 'Which of the following is recognized as a major development benefit of conducting an Environmental Impact Assessment?',
    choices: [
      'It completely removes all environmental standards for foreign investors',
      'It provides a structured, scientific mechanism to evaluate trade-offs, optimize resource efficiency, and avoid catastrophic post-construction remediation costs',
      'It guarantees that projects will never produce any carbon emissions',
      'It replaces the need for municipal courts and legal contracts',
    ],
    answer: 1,
    explanation: 'EIA allows engineers and decision-makers to evaluate design alternatives, minimize raw material consumption, prevent irreversible ecological collapses, and avoid immense post-construction liabilities and expensive retrofitting.',
    takeaway: 'EIA enables sound development planning, resource optimization, and prevention of irreversible environmental harm.',
  },
  {
    id: 'warm-q15',
    module: 'warming',
    topic: 'Recognized Flaws & Limitations of EIA',
    difficulty: 'Expert',
    prompt: 'According to the curriculum review of EIA practice in developing countries, what is widely cited as a major operational flaw or weakness?',
    choices: [
      'The process is completed too quickly without any engineering review',
      'Unavailability of reliable baseline data, protracted project delays, and weak post-clearance compliance monitoring in practice',
      'Public hearings are prohibited by law in all developing countries',
      'EIA reports are never allowed to be printed in native languages',
    ],
    answer: 1,
    explanation: 'Major recognized weaknesses of EIA include: (1) scarcity of reliable long-term historical baseline data in developing nations, (2) prolonged procedural delays, (3) significant upfront consultancy costs, and critically, (4) poor institutional mechanisms to monitor and enforce compliance conditions after clearances are granted.',
    takeaway: 'Data deficiencies, lengthy delays, and lax post-clearance compliance monitoring remain key limitations of EIA.',
  },
];
