export type QuizQuestion = {
  id?: string;
  module: string;
  topic?: string;
  difficulty?: 'Standard' | 'Advanced' | 'Expert';
  sectionId?: string;
  prompt: string;
  choices: string[];
  answer: number;
  explanation: string;
  takeaway?: string;
};

export const quizQuestions: QuizQuestion[] = [
  // ==========================================
  // MODULE 01: LAND (15 Comprehensive Questions)
  // ==========================================
  {
    id: 'land-q01',
    module: 'land',
    sectionId: 'ch-formation',
    topic: 'Cosmic Accretion & Earth Formation',
    difficulty: 'Standard',
    prompt: 'According to planetary accretion records, approximately how long ago did the Earth form?',
    choices: [
      '4.6 million years ago',
      '4.6 billion years ago',
      '46 billion years ago',
      '460 million years ago',
    ],
    answer: 1,
    explanation: 'The Earth formed approximately 4.6 billion years ago (4,600 Ma) from gravitational accretion of cosmic dust, meteorites, and planetesimals within the solar nebula.',
    takeaway: 'Earth is 4.6 billion years old, undergoing early core differentiation and atmospheric degassing.',
  },
  {
    id: 'land-q02',
    module: 'land',
    sectionId: 'ch-layers',
    topic: 'Earth Internal Structure',
    difficulty: 'Advanced',
    prompt: 'Which mechanical layer of Earth is composed of semi-fluid, plastic rock upon which the rigid lithospheric plates drift?',
    choices: [
      'Lithosphere',
      'Asthenosphere',
      'Outer Core',
      'Inner Core',
    ],
    answer: 1,
    explanation: 'The asthenosphere is the ductile, semi-fluid upper mantle layer (~100 to 660 km deep) whose thermal convection currents drive continental drift and tectonic activity.',
    takeaway: 'The rigid lithosphere floats and drifts across the plastic, convecting asthenosphere.',
  },
  {
    id: 'land-q03',
    module: 'land',
    sectionId: 'ch-continents',
    topic: 'Plate Tectonics & Continental Drift',
    difficulty: 'Standard',
    prompt: 'What was the name of the unified supercontinent that existed ~250 million years ago before rifting into Laurasia and Gondwanaland?',
    choices: [
      'Rodinia',
      'Pangaea',
      'Panthalassa',
      'Columbia',
    ],
    answer: 1,
    explanation: 'Alfred Wegener proposed that ~250 million years ago, all landmasses coalesced into the supercontinent Pangaea, encircled by the vast Panthalassa ocean, before breaking apart.',
    takeaway: 'Pangaea rifted apart via tectonic movement to form our modern continents.',
  },
  {
    id: 'land-q04',
    module: 'land',
    sectionId: 'ch-resource',
    topic: 'Planetary Land Allocation',
    difficulty: 'Standard',
    prompt: 'What percentage of the Earth’s total surface area is land, and approximately how much of that land is directly habitable?',
    choices: [
      '29% land surface, of which ~71% is habitable',
      '50% land surface, of which ~90% is habitable',
      '20% land surface, of which ~50% is habitable',
      '71% land surface, of which ~29% is habitable',
    ],
    answer: 0,
    explanation: 'Land covers roughly 29.2% of Earth (149 million km²), with oceans covering 70.8%. Of this total land area, approximately 71% is habitable, while 29% comprises glaciers, barren deserts, and high peaks.',
    takeaway: 'Habitable land is a strictly finite planetary boundary supporting 8+ billion people.',
  },
  {
    id: 'land-q05',
    module: 'land',
    sectionId: 'ch-soil',
    topic: 'Soil Formation (Pedogenesis)',
    difficulty: 'Advanced',
    prompt: 'What is the fundamental scientific difference between weathering and pedogenesis?',
    choices: [
      'Weathering produces organic humus; pedogenesis only crushes boulders',
      'Weathering breaks parent rock into mineral fragments; pedogenesis is the maturation of true soil with humus and horizons',
      'Weathering occurs only in tropical climates; pedogenesis occurs exclusively in polar ice caps',
      'There is no distinction; they are synonymous terms in earth science',
    ],
    answer: 1,
    explanation: 'Weathering (physical, chemical, biological) disintegrates solid bedrock into mineral regolith. Pedogenesis is the multi-generational biochemical process that develops distinct soil horizons and incorporates organic humus.',
    takeaway: 'Soil = Weathered Mineral Parent Material + Biological Pedogenesis over centuries.',
  },
  {
    id: 'land-q06',
    module: 'land',
    sectionId: 'ch-soil',
    topic: 'Soil Horizons Profile',
    difficulty: 'Advanced',
    prompt: 'In a mature soil profile, which master horizon is known as the zone of eluviation (maximum leaching of clay, iron, and minerals)?',
    choices: [
      'O Horizon (Organic humus layer)',
      'A Horizon (Topsoil)',
      'E Horizon (Eluviated leached layer)',
      'C Horizon (Parent rock regolith)',
    ],
    answer: 2,
    explanation: 'The E horizon (from French "éluvier" = to wash out) is a heavily leached layer occurring below the A horizon, where downward percolating water removes clays, iron, and organic acids, leaving bleached silicates.',
    takeaway: 'The E Horizon is the zone of eluviation; the underlying B Horizon is the zone of illuviation (accumulation).',
  },
  {
    id: 'land-q07',
    module: 'land',
    sectionId: 'ch-landforms',
    topic: 'Geomorphology & Landforms',
    difficulty: 'Standard',
    prompt: 'Which topographic feature distinguishes a plateau from a mountain range?',
    choices: [
      'Plateaus are created solely by coral reef deposition',
      'Plateaus have an elevated, relatively level tableland summit bounded by steep escarpments',
      'Mountains are always lower in elevation than surrounding plains',
      'Plateaus are characterized by sharply pointed volcanic peaks',
    ],
    answer: 1,
    explanation: 'A plateau is an elevated landform with a relatively flat top (tableland) that rises sharply above adjacent plains on at least one side (e.g., the Deccan Plateau, Colorado Plateau).',
    takeaway: 'Plateaus feature expansive elevated flat summits, whereas mountains have steep gradients and sharp summits.',
  },
  {
    id: 'land-q08',
    module: 'land',
    sectionId: 'ch-conservation',
    topic: 'Landform Conservation',
    difficulty: 'Standard',
    prompt: 'Which landscape conservation strategy maintains gene flow and animal migration across fragmented natural landforms?',
    choices: [
      'Ecological Wildlife Corridors & Habitat Linkages',
      'Perimeter clear-cutting of buffer zones',
      'Complete monoculture pine planting',
      'Fencing off every mountain ridge with concrete walls',
    ],
    answer: 0,
    explanation: 'Ecological corridors connect isolated forest patches and mountain ridges, allowing large mammals, pollinators, and seeds to migrate safely, preventing genetic isolation and local extinctions.',
    takeaway: 'Corridors counteract habitat fragmentation by maintaining continuous ecological connectivity.',
  },
  {
    id: 'land-q09',
    module: 'land',
    sectionId: 'ch-deforestation',
    topic: 'Deforestation & Forest Ecology',
    difficulty: 'Standard',
    prompt: 'Globally, what single human activity is recognized by the FAO as the primary driver of tropical deforestation?',
    choices: [
      'Commercial agriculture (cattle ranching, soybean cultivation, and oil palm plantations)',
      'Construction of rural single-family housing',
      'Underground geothermal energy wells',
      'Urban park development',
    ],
    answer: 0,
    explanation: 'Commercial agriculture accounts for approximately 73% of tropical deforestation, driven primarily by cattle ranching (beef) in South America and oil palm/soy cultivation in Southeast Asia and the Amazon.',
    takeaway: 'Agricultural commodity expansion is the single greatest driver of worldwide forest clearing.',
  },
  {
    id: 'land-q10',
    module: 'land',
    sectionId: 'ch-landuse',
    topic: 'Land-Use Change & Hydrology',
    difficulty: 'Expert',
    prompt: 'In the Shire River Basin case study, what was the direct downstream consequence of upstream deforestation and steep hillside farming?',
    choices: [
      'The river completely evaporated within three weeks',
      'Massive sediment loading and siltation that choked hydroelectric turbine intakes at Nkula and Tedzani',
      'Sudden freezing of the lower wetlands into glacier ice',
      'Transformation of the river bed into solid volcanic basalt',
    ],
    answer: 1,
    explanation: 'Deforestation and uncontrolled slope cultivation in the upper Shire catchment caused catastrophic topsoil erosion. Torrential rains carried hundreds of thousands of tons of sediment into the river, choking cooling water and turbine intakes at Nkula and Tedzani power plants, triggering nationwide blackouts in Malawi.',
    takeaway: 'Watershed deforestation directly threatens downstream clean energy, reservoir storage, and municipal water security.',
  },
  {
    id: 'land-q11',
    module: 'land',
    sectionId: 'ch-soilhealth',
    topic: 'Soil Health & Composition',
    difficulty: 'Standard',
    prompt: 'What is the volumetric breakdown of an ideal, healthy agricultural soil matrix?',
    choices: [
      '45% Mineral particles, 25% Air, 25% Water, 5% Organic matter',
      '70% Mineral particles, 10% Air, 10% Water, 10% Organic matter',
      '30% Mineral particles, 35% Air, 30% Water, 5% Organic matter',
      '50% Mineral particles, 40% Air, 5% Water, 5% Organic matter',
    ],
    answer: 0,
    explanation: 'An optimal agricultural soil profile comprises 45% mineral solids (sand, silt, clay), 50% pore space evenly divided between 25% air and 25% water, and 5% organic matter (80% humus, 10% roots, 10% active soil organisms).',
    takeaway: 'The 45-25-25-5 balance ensures root aeration, adequate water retention, and microbial nutrient cycling.',
  },
  {
    id: 'land-q12',
    module: 'land',
    sectionId: 'ch-degradation',
    topic: 'Land Degradation Pathways',
    difficulty: 'Advanced',
    prompt: 'How does excessive furrow irrigation in arid climates cause severe secondary soil salinization?',
    choices: [
      'By freezing the soil profile below the root zone',
      'Capillary draw pulls dissolved mineral salts upward as rapid surface evaporation leaves salt crusts behind',
      'By leaching all mineral salts into the lower mantle',
      'By permanently converting clay minerals into pure silica sand',
    ],
    answer: 1,
    explanation: 'Over-irrigation in arid regions raises groundwater tables. In intense heat, water evaporates quickly from the surface, causing upward capillary suction that brings dissolved sodium, calcium, and magnesium salts to the topsoil, where they crystallize into toxic saline crusts.',
    takeaway: 'Capillary action coupled with rapid evaporation drives agricultural salinization in drylands.',
  },
  {
    id: 'land-q13',
    module: 'land',
    sectionId: 'ch-soilconservation',
    topic: 'Soil Conservation Strategies',
    difficulty: 'Standard',
    prompt: 'Which soil conservation strategy involves plowing and planting crops along lines of equal elevation across a slope?',
    choices: [
      'Contour Farming (Contour Plowing)',
      'Vertical furrowing directly down the hillside',
      'Continuous stubble burning',
      'Deep subsoil bedrock blasting',
    ],
    answer: 0,
    explanation: 'Contour farming follows natural elevation contours, creating horizontal ridges that act as micro-terraces, trapping runoff, allowing infiltration, and reducing soil erosion by up to 50% compared to up-and-down plowing.',
    takeaway: 'Contour plowing slows surface runoff velocities and traps eroding sediment on slopes.',
  },
  {
    id: 'land-q14',
    module: 'land',
    sectionId: 'ch-planning',
    topic: 'Sustainable Land-Use Planning (SLUP)',
    difficulty: 'Expert',
    prompt: 'In the Nilgiris Western Ghats case study, what key planning principle was recommended to curb catastrophic monsoonal landslides?',
    choices: [
      'Clearing all native shola trees to plant eucalyptus monocultures',
      'Slope-angle zoning, prohibition of unscientific hillside cutting, and restoration of native shola-grassland buffers',
      'Paving all agricultural hillsides with concrete slabs',
      'Channeling monsoon torrents through residential basements',
    ],
    answer: 1,
    explanation: 'Sustainable planning in fragile hill regions like the Nilgiris requires slope-angle zoning (restricting building on slopes >30°), regulating road excavation, mandating retaining walls, and preserving native deep-rooted shola vegetation that anchors colluvial soil.',
    takeaway: 'Land-use zoning must align with geophysical slope stability and watershed boundaries.',
  },
  {
    id: 'land-q15',
    module: 'land',
    sectionId: 'ch-summary',
    topic: 'Global Frameworks & SDG Target',
    difficulty: 'Standard',
    prompt: 'Target 15.3 of the United Nations Sustainable Development Goals commits global nations to achieve what specific outcome by 2030?',
    choices: [
      'Complete urbanization of 80% of all national parks',
      'Land Degradation Neutrality (LDN) and restoration of degraded soils',
      'Conversion of all natural wetlands into freshwater fish farms',
      'Diverting 70% of river flows into industrial canals',
    ],
    answer: 1,
    explanation: 'UN SDG Target 15.3 calls on all member nations to combat desertification, restore degraded land and soil (including areas affected by desertification, drought, and floods), and strive to achieve a Land Degradation Neutral (LDN) world by 2030.',
    takeaway: 'SDG 15.3 establishes Land Degradation Neutrality (LDN) as a cornerstone of planetary health.',
  },

  // ==========================================
  // MODULE 02: WATER
  // ==========================================
  {
    id: 'water-q01',
    module: 'water',
    topic: 'Hydrological Distribution',
    prompt: 'What proportion of Earth’s total water volume is freshwater in the supplied notes?',
    choices: ['20%', '2.5%', '1%', '79%'],
    answer: 1,
    explanation: 'The course notes give 97.5% saltwater in oceans and 2.5% freshwater, of which nearly 69% is locked in glaciers and ice caps.',
    takeaway: 'Freshwater represents only 2.5% of total global water volume.',
  },
  {
    id: 'water-q02',
    module: 'water',
    topic: 'Hydrogeology',
    prompt: 'What is an aquifer in hydrogeological terms?',
    choices: [
      'A surface river basin boundary line',
      'An underground rock or sediment formation that stores and transmits usable quantities of groundwater',
      'A surface-water municipal treatment plant',
      'A coastal tidal saltwater wedge',
    ],
    answer: 1,
    explanation: 'An aquifer is a permeable subterranean rock, sand, or gravel formation capable of storing and yielding groundwater to wells and springs.',
    takeaway: 'Aquifers are subterranean water storage systems vital for human survival.',
  },
  {
    id: 'water-q03',
    module: 'water',
    topic: 'River Basins',
    prompt: 'Which is one of the six major Indian river-basin groups identified in the notes?',
    choices: ['Western-coast rivers', 'Arctic rivers', 'Nile river system', 'Central Asian rivers'],
    answer: 0,
    explanation: 'The course notes categorize Indian river systems into six major groups including Western-coast rivers, Indus, Ganga, Brahmaputra, Peninsular east-flowing, and Inland drainage.',
    takeaway: 'Western-coast rivers form one of India’s six primary river basin classifications.',
  },
  {
    id: 'water-q04',
    module: 'water',
    topic: 'Groundwater Recharge',
    prompt: 'Which method is an artificial groundwater-recharge technique highlighted in the curriculum?',
    choices: ['Percolation tank', 'Cloud seeding only', 'Deep coastal pumping trough', 'Ocean surface evaporation'],
    answer: 0,
    explanation: 'Percolation tanks are excavated surface basins constructed across natural streams to impound monsoon runoff and promote artificial recharge into underlying aquifers.',
    takeaway: 'Percolation tanks capture surface runoff to replenish declining water tables.',
  },

  // ==========================================
  // MODULE 03: AIR
  // ==========================================
  {
    id: 'air-q01',
    module: 'air',
    topic: 'Atmospheric Composition',
    prompt: 'Which three gases make up about 99% of dry air in the lower atmosphere?',
    choices: [
      'Nitrogen, oxygen and argon',
      'Oxygen, carbon dioxide and methane',
      'Nitrogen, ozone and helium',
      'Argon, neon and water vapour',
    ],
    answer: 0,
    explanation: 'Nitrogen (~78.08%), Oxygen (~20.95%), and Argon (~0.93%) account for more than 99.9% of dry atmospheric gases.',
    takeaway: 'Nitrogen, oxygen, and argon form the bulk of dry atmospheric air.',
  },
  {
    id: 'air-q02',
    module: 'air',
    topic: 'Atmospheric Pollutants',
    prompt: 'What distinguishes a secondary air pollutant from a primary air pollutant?',
    choices: [
      'It is always in solid particulate form',
      'It forms in the atmosphere through chemical or photochemical reactions among precursors',
      'It originates exclusively from natural volcanic sources',
      'It is emitted only by stationary point stacks',
    ],
    answer: 1,
    explanation: 'Secondary pollutants (such as tropospheric ozone and peroxyacetyl nitrate - PAN) are not emitted directly but form when primary pollutants react under sunlight in the atmosphere.',
    takeaway: 'Secondary pollutants form via atmospheric chemical reactions.',
  },
  {
    id: 'air-q03',
    module: 'air',
    topic: 'Air Quality Index',
    prompt: 'Which numerical AQI range is categorized as "Severe" in the standard Indian AQI scale?',
    choices: ['0–50', '101–200', '301–400', '401–500'],
    answer: 3,
    explanation: 'The Indian National Air Quality Index designates 401–500 as "Severe", warning of serious health impacts on healthy people and severe impacts on those with existing diseases.',
    takeaway: 'An AQI of 401–500 is classified as Severe.',
  },
  {
    id: 'air-q04',
    module: 'air',
    topic: 'Pollution Control Technology',
    prompt: 'Which industrial emission control equipment uses high-voltage electrostatic charges to remove fine particulate matter from flue gases?',
    choices: [
      'Electrostatic precipitator (ESP)',
      'Cyclone separator',
      'Wet scrubber',
      'Thermal afterburner',
    ],
    answer: 0,
    explanation: 'An Electrostatic Precipitator (ESP) ionizes suspended particulates with high-voltage electrodes and collects them on oppositely charged grounded plates with >99% efficiency.',
    takeaway: 'ESPs use high-voltage electrical fields to precipitate fly ash and particulates.',
  },

  // ==========================================
  // MODULE 04: BIODIVERSITY
  // ==========================================
  {
    id: 'bio-q01',
    module: 'biodiversity',
    topic: 'Biodiversity Hierarchy',
    prompt: 'What are the three canonical levels of biodiversity recognized in conservation biology?',
    choices: [
      'Genetic, species, and ecosystem diversity',
      'Plant, animal, and mineral diversity',
      'Local, regional, and global diversity',
      'Forest, grassland, and desert diversity',
    ],
    answer: 0,
    explanation: 'Biodiversity is structured across three fundamental organizational tiers: genetic diversity (within species), species diversity (between species), and ecosystem diversity (across communities).',
    takeaway: 'Genetic, species, and ecosystem diversity constitute the three tiers of life on Earth.',
  },
  {
    id: 'bio-q02',
    module: 'biodiversity',
    topic: 'Conservation Strategies',
    prompt: 'What is in-situ biodiversity conservation?',
    choices: [
      'Conservation of wild species within their natural ecosystems and habitats',
      'Preservation of seeds exclusively inside cryogenic seed vaults',
      'Commercial breeding in private laboratory facilities',
      'Replanting botanical gardens in urban centers',
    ],
    answer: 0,
    explanation: 'In-situ conservation protects populations of species within their natural evolutionary ecosystems (e.g., National Parks, Biosphere Reserves, Wildlife Sanctuaries).',
    takeaway: 'In-situ conservation preserves species directly inside their natural habitats.',
  },
  {
    id: 'bio-q03',
    module: 'biodiversity',
    topic: 'Biodiversity Values',
    prompt: 'Which is one of the recognized biodiversity value categories in environmental economics?',
    choices: [
      'Option value',
      'Screening value',
      'Hydrologic value',
      'Mechanical value',
    ],
    answer: 0,
    explanation: 'Biodiversity values encompass consumptive, productive, social, ethical, aesthetic, and option value (the value of preserving species for potential future unforeseen medical or agricultural discoveries).',
    takeaway: 'Option value reflects the future potential utility of preserved biological resources.',
  },
  {
    id: 'bio-q04',
    module: 'biodiversity',
    topic: 'Aquatic Ecosystems',
    prompt: 'Which zone of a freshwater lake ecosystem is situated nearest to the shore and supports rooted vegetation?',
    choices: ['Profundal zone', 'Littoral zone', 'Limnetic zone', 'Benthic zone'],
    answer: 1,
    explanation: 'The littoral zone is the shallow, well-lit near-shore region of a lake where sunlight penetrates to the bottom, allowing emergent and submerged macrophytes to thrive.',
    takeaway: 'The littoral zone is the shallow, nutrient-rich near-shore lake region.',
  },

  // ==========================================
  // MODULE 05: GLOBAL WARMING
  // ==========================================
  {
    id: 'warm-q01',
    module: 'warming',
    topic: 'Planetary Energy Balance',
    prompt: 'According to planetary radiative equilibrium calculations, about how much incoming solar radiation is directly reflected back into space (albedo)?',
    choices: ['10%', '30%', '50%', '70%'],
    answer: 1,
    explanation: 'Earth’s global albedo is approximately 0.30 (30%), reflecting incoming sunlight back to space through clouds, atmospheric aerosols, and reflective surfaces (ice, snow, deserts).',
    takeaway: 'Earth reflects roughly 30% of incoming solar energy and absorbs 70%.',
  },
  {
    id: 'warm-q02',
    module: 'warming',
    topic: 'Greenhouse Effect',
    prompt: 'What are the estimated global mean surface temperatures of Earth WITHOUT and WITH the natural greenhouse effect?',
    choices: [
      '−18°C without, and +15°C with',
      '+15°C without, and +30°C with',
      '0°C without, and +18°C with',
      '−30°C without, and +18°C with',
    ],
    answer: 0,
    explanation: 'Without the natural greenhouse effect, Earth would have an average temperature of approximately −18°C (frozen planet). The natural absorption of terrestrial infrared by water vapor and CO2 warms it by +33°C to our current hospitable +15°C.',
    takeaway: 'The natural greenhouse effect warms Earth from −18°C to an average +15°C.',
  },
  {
    id: 'warm-q03',
    module: 'warming',
    topic: 'Environmental Impact Assessment',
    prompt: 'Which are the three core ethical values governing Environmental Impact Assessment (EIA)?',
    choices: [
      'Integrity, utility, and sustainability',
      'Speed, cost-reduction, and deregulation',
      'Air quality, water volume, and land acreage',
      'Screening, scoping, and public notices',
    ],
    answer: 0,
    explanation: 'The International Association for Impact Assessment (IAIA) defines the three foundational core values of EIA as integrity (fairness and professional rigor), utility (balanced decision-making), and sustainability (protecting future generations).',
    takeaway: 'Integrity, utility, and sustainability are the three core values of EIA.',
  },
  {
    id: 'warm-q04',
    module: 'warming',
    topic: 'EIA Sequence',
    prompt: 'In the standard nine-phase EIA sequence, which critical planning document is formulated following the public hearing?',
    choices: [
      'Screening application',
      'Environmental Management Plan (EMP)',
      'Baseline data collection',
      'Initial Terms of Reference Scoping',
    ],
    answer: 1,
    explanation: 'Following the mandatory public consultation and hearing phase, project developers synthesize public inputs to prepare the comprehensive Environmental Management Plan (EMP) detailing mitigation and monitoring measures.',
    takeaway: 'The Environmental Management Plan (EMP) directly incorporates outcomes from public hearings.',
  },
];
