import type { ModuleContent } from './types';

const warming: ModuleContent = {
  id: 5,
  slug: 'warming',
  name: 'Global Warming & EIA',
  shortName: 'WARMING & EIA',
  tagline: 'A balance under stress.',
  subtitle: 'Trace the heat — then follow the process that asks what a project may change.',
  accent: '#D8703F',
  image: '/images/world-warming.webp',
  noteFile: '/notes/module-05-warming-eia.md',
  noteLabel: 'Module 05 · Global warming & EIA study notes',
  chapters: [
    { id: 'ch-01', part: 'PART 01 · 1.1', title: 'The greenhouse effect, in motion', deck: 'Adjust the greenhouse-gas slider. Sunlight comes in; some outgoing heat is absorbed and re-radiated.', kind: 'greenhouse', facts: [{ label: 'Sunlight reflected', value: '~30%' }, { label: 'Sunlight absorbed', value: '~70%' }, { label: 'Without natural greenhouse effect', value: 'About −18°C' }, { label: 'Present average in notes', value: 'About +15°C' }], bullets: ['Global warming is the gradual rise in the average temperature of Earth’s atmosphere and oceans.', 'Natural greenhouse gases include CO₂, water vapour, ozone and methane; the natural greenhouse effect makes life possible.', 'The problem begins when excess greenhouse gases trap additional outgoing heat.'] },
    { id: 'ch-02', part: 'PART 01 · 1.2', title: 'Ten signals of a warming planet', deck: 'These indicators are presented as directional signals in the supplied course notes.', kind: 'warming-indicators', facts: [{ label: 'Indicators', value: '10' }, { label: 'Direction', value: 'Some rise; ice and snow measures fall' }], bullets: ['Air-surface temperature · specific humidity · glaciers · snow cover · temperature over land.', 'Sea-surface temperature · sea ice · sea level · ocean heat content · temperature over oceans.', 'The small trend marks are illustrative summaries of direction, not measured time series.'] },
    { id: 'ch-03', part: 'PART 01 · 1.3', title: 'The drivers', deck: 'Select a driver to trace its sources. The contribution strip follows the summary in the course notes.', kind: 'warming-causes', facts: [{ label: 'CO₂', value: '~80% (notes)' }, { label: 'CH₄ + N₂O', value: 'Remaining ~20% (notes)' }, { label: 'Other factor', value: 'Deforestation' }], bullets: ['The notes identify carbon dioxide, methane, nitrous oxide and deforestation as major factors.', 'Sources discussed include fossil-fuel power, transport, industry, agriculture, livestock, waste and land-use change.', 'The percentages shown here are reproduced from the supplied notes, not presented as a current emissions inventory.'] },
    { id: 'ch-04', part: 'PART 01 · 1.4', title: 'A chain of consequences', deck: 'Warming connects physical changes to water, food, ecosystems and health.', kind: 'warming-effects', facts: [{ label: 'Examples in notes', value: 'Heat · rainfall shifts · sea-level rise · storms · drought' }], bullets: ['The notes describe melting ice, rising sea levels, extreme weather, ecosystem shifts and health impacts.', 'Changes in temperature and precipitation affect agriculture and water availability.', 'Coral bleaching, food shortages and disease spread are also listed among possible effects.'] },
    { id: 'ch-05', part: 'PART 02 · 2.1', title: 'Warming is one signal. Climate is the pattern.', deck: 'Global warming is a change in average temperature; climate change describes broader, long-term shifts in climate patterns.', kind: 'warming-vs-climate', facts: [{ label: 'Global warming', value: 'Long-term rise in average temperature' }, { label: 'Climate change', value: 'Broader, long-term pattern shifts' }], bullets: ['The two ideas are related but not interchangeable.', 'Warming can influence precipitation, winds, storms, ice, oceans, ecosystems and health.', 'Climate describes patterns over time, rather than only a single day’s weather.'] },
    { id: 'ch-06', part: 'PART 02 · 2.2', title: 'Eight climate indicators', deck: 'Choose an indicator to see how it expresses a broader climate shift.', kind: 'climate-indicators', facts: [{ label: 'Indicators', value: '8' }], bullets: ['Global warming · polar and glacial ice changes · ocean acidity · climate and health.', 'Changing wind patterns · changing precipitation patterns · storm intensity and frequency · changing biomes.', 'The selector is a learning diagram; it does not display live climate data.'] },
    { id: 'ch-07', part: 'PART 02 · 2.3', title: 'Climate is also a health story', deck: 'Connect a climate driver to a health outcome.', kind: 'climate-health', facts: [{ label: 'Pathways', value: 'Heat stress · disease · air quality · water and food' }], bullets: ['The notes discuss heat-related illness, changing disease patterns and impacts on air quality.', 'Changing rainfall, water availability and food systems can create additional health pressures.', 'Impacts vary by place, exposure, health status and adaptive capacity.'] },
    { id: 'ch-08', part: 'PART 03 · 3.1', title: 'Before we build, we assess', deck: 'Environmental Impact Assessment studies the likely environmental consequences of a proposed project before a decision is made.', kind: 'eia-intro', facts: [{ label: 'EIA', value: 'Environmental Impact Assessment' }, { label: 'Purpose', value: 'Inform decisions; identify impacts and mitigation' }], bullets: ['The notes describe EIA as a study to predict the effect of a proposed project on the environment.', 'EIA examines environmental consequences and helps decision-makers consider alternatives and mitigation.', 'The visual language shifts here from heat and atmosphere to a calm assessment blueprint.'] },
    { id: 'ch-09', part: 'PART 03 · 3.2', title: 'Three values at the core', deck: 'Integrity, utility and sustainability are the three core values set out in the notes.', kind: 'eia-values', facts: [{ label: '01', value: 'Integrity' }, { label: '02', value: 'Utility' }, { label: '03', value: 'Sustainability' }], bullets: ['Integrity: the assessment should be credible and complete.', 'Utility: the process should inform decisions and be useful to those making them.', 'Sustainability: environmental considerations should support long-term outcomes.'] },
    { id: 'ch-10', part: 'PART 03 · 3.3–3.4', title: 'A process that travelled', deck: 'The course notes trace EIA from its US origins to wider adoption and practice in India.', kind: 'eia-history', facts: [{ label: 'United States', value: 'NEPA · 1969; implementation in 1970' }, { label: 'Global spread', value: 'Widely adopted over subsequent decades' }, { label: 'India', value: 'EIA developed through national policy and project assessment' }], bullets: ['Environmental assessment became part of decision-making through legislation and policy.', 'The notes mention the World Bank’s role in the 1980s and adoption by 100+ countries.', 'Benefits include structured assessment, alternatives, public participation, coordination and informed decisions.'] },
    { id: 'ch-11', part: 'PART 03 · 3.5', title: 'Nine phases. One decision trail.', deck: 'Select a phase to see what happens. The progress rail follows your selection.', kind: 'eia-process', facts: [{ label: 'Phases', value: '9' }, { label: 'Public participation', value: 'Public hearing' }, { label: 'After approval', value: 'Monitoring clearance conditions' }], bullets: ['Screening → scoping → baseline data collection → impact analysis.', 'Alternatives, mitigation and EIA report → public hearing → Environmental Management Plan.', 'Decision-making → monitoring of clearance conditions.'] },
    { id: 'ch-12', part: 'PART 03 · 3.6', title: 'The process is not always a straight line', deck: 'Follow the route from screening through review and decision. A project may need to revisit its evidence or mitigation.', kind: 'eia-flowchart', facts: [{ label: 'Flow', value: 'Screen → assess → consult → decide → monitor' }], bullets: ['The supplied notes describe decision branches in the EIA flowchart.', 'Assessment informs whether a project should proceed, be redesigned or require more work.', 'Monitoring checks whether clearance conditions are followed.'] },
    { id: 'ch-13', part: 'PART 03 · 3.7', title: 'Inside an EIA report', deck: 'Explore the eight report components. Each one connects to a course module.', kind: 'eia-report', facts: [{ label: 'Components', value: 'A–H · Air, Noise, Water, Biological, Land, Socio-economic & Health, Risk, EMP' }], bullets: ['Air · Noise · Water · Biological environment.', 'Land · Socio-economic and health environment · Risk assessment · Environment Management Plan.', 'The supplied notes distinguish comprehensive EIA from rapid EIA; the depth and time period of baseline study differ.'] },
    { id: 'ch-14', part: 'PART 03 · 3.8', title: 'A useful tool — with limits', deck: 'Compare the benefits and flaws side by side. The point is not that assessment is perfect, but that its quality and follow-through matter.', kind: 'eia-benefits', facts: [{ label: 'Strengths', value: 'Structured analysis · alternatives · public participation' }, { label: 'Challenges', value: 'Time · cost · data gaps · weak follow-up' }], bullets: ['Benefits in the notes include systematic assessment, coordination, environmental integration and feedback.', 'Flaws include time and cost, limited participation in implementation, unreliable data and inadequate monitoring.', 'The final responsibility continues after the report: clearance conditions need to be monitored.'] },
  ],
  recap: [{ label: 'Sunlight reflected', value: '~30%' }, { label: 'Sunlight absorbed', value: '~70%' }, { label: 'EIA values', value: '3' }, { label: 'EIA phases', value: '9' }],
};
export default warming;
